-- Drop the existing table and recreate it to ensure a clean slate
DROP TABLE IF EXISTS public.words CASCADE;

-- Clear existing progress data since the word IDs will be completely remapped
TRUNCATE TABLE public.user_progress;

CREATE TABLE public.words (
    id SERIAL PRIMARY KEY,
    en TEXT NOT NULL,
    es TEXT NOT NULL,
    type TEXT,
    ex TEXT,
    p INTEGER NOT NULL,
    lvl INTEGER DEFAULT 0,
    conjugations JSONB,
    tags JSONB DEFAULT '[]'::jsonb
);

-- Turn on Row Level Security
ALTER TABLE public.words ENABLE ROW LEVEL SECURITY;

-- Allow read access to all authenticated users
CREATE POLICY "Enable read access for all authenticated users"
ON public.words FOR SELECT
TO authenticated USING (true);

INSERT INTO public.words (en, es, type, ex, p, lvl, conjugations, tags) VALUES
  ('el/la', 'the', 'article', 'El perro y la gata juegan.', 1, 0, NULL, '[]'::jsonb),
  ('un/una', 'a/an', 'article', 'Quiero una manzana y un plátano.', 1, 0, NULL, '[]'::jsonb),
  ('de', 'of/from', 'preposition', 'Soy de Madrid.', 1, 0, NULL, '[]'::jsonb),
  ('que', 'that/which', 'conjunction', 'El libro que leí es bueno.', 1, 0, NULL, '[]'::jsonb),
  ('y', 'and', 'conjunction', 'Tú y yo somos amigos.', 1, 0, NULL, '[]'::jsonb),
  ('en', 'in/on/at', 'preposition', 'Estamos en la casa.', 1, 0, NULL, '[]'::jsonb),
  ('a', 'to/at', 'preposition', 'Voy a la escuela.', 1, 0, NULL, '[]'::jsonb),
  ('ser', 'to be', 'verb', 'Quiero ser doctor.', 1, 0, '''{"yo":"soy","tu":"eres","el":"es","nosotros":"somos","vosotros":"sois","ellos":"son","gerundio":"siendo"}''::jsonb'::jsonb, '["regular irr."]'::jsonb),
  ('él/ella', 'he/she', 'pronoun', 'Él es alto y ella es baja.', 1, 0, NULL, '[]'::jsonb),
  ('no', 'no/not', 'adverb', 'No quiero salir hoy.', 1, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('tener', 'to have', 'verb', 'Tengo un coche nuevo.', 1, 0, '''{"yo":"tengo","tu":"tienes","el":"tiene","nosotros":"tenemos","vosotros":"tenéis","ellos":"tienen","gerundio":"teniendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('un/uno', 'one', 'number', 'Solo tengo un hermano.', 1, 0, NULL, '[]'::jsonb),
  ('por', 'for/by', 'preposition', 'Gracias por tu ayuda.', 1, 0, NULL, '[]'::jsonb),
  ('con', 'with', 'preposition', 'Voy al cine con mis amigos.', 1, 0, NULL, '[]'::jsonb),
  ('su', 'his/her/their', 'determiner', 'Su casa es muy grande.', 1, 0, NULL, '[]'::jsonb),
  ('para', 'for/in order to', 'preposition', 'Este regalo es para ti.', 1, 0, NULL, '[]'::jsonb),
  ('como', 'like/as', 'conjunction', 'Eres fuerte como un toro.', 1, 0, NULL, '[]'::jsonb),
  ('estar', 'to be', 'verb', 'Estoy muy cansado.', 1, 0, '''{"yo":"estoy","tu":"estás","el":"está","nosotros":"estamos","vosotros":"estáis","ellos":"están","gerundio":"estando"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('me', 'me/myself', 'pronoun', 'Me gusta mucho la música.', 1, 0, NULL, '[]'::jsonb),
  ('más', 'more', 'adverb', 'Quiero más agua, por favor.', 1, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('lo', 'it/him', 'pronoun', 'Lo vi ayer en el supermercado.', 1, 0, NULL, '[]'::jsonb),
  ('o', 'or', 'conjunction', '¿Quieres té o café?', 1, 0, NULL, '[]'::jsonb),
  ('pero', 'but', 'conjunction', 'Es caro, pero es bueno.', 1, 0, NULL, '[]'::jsonb),
  ('hacer', 'to do/to make', 'verb', 'Tengo que hacer mi tarea.', 1, 0, '''{"yo":"hago","tu":"haces","el":"hace","nosotros":"hacemos","vosotros":"hacéis","ellos":"hacen","gerundio":"haciendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('le', 'to him/her/it', 'pronoun', 'Le di el libro a Juan.', 1, 0, NULL, '[]'::jsonb),
  ('poder', 'to be able to/can', 'verb', '¿Puedo ir al baño?', 1, 0, '''{"yo":"puedo","tu":"puedes","el":"puede","nosotros":"podemos","vosotros":"podéis","ellos":"pueden","gerundio":"pudiendo"}''::jsonb'::jsonb, '["irregular o->ue"]'::jsonb),
  ('decir', 'to say/tell', 'verb', 'Tienes que decir la verdad.', 1, 0, '''{"yo":"digo","tu":"dices","el":"dice","nosotros":"decimos","vosotros":"decís","ellos":"dicen","gerundio":"diciendo"}''::jsonb'::jsonb, '["irregular e->i"]'::jsonb),
  ('este/esta', 'this', 'determiner', 'Este coche es muy rápido.', 1, 0, NULL, '[]'::jsonb),
  ('ir', 'to go', 'verb', 'Voy a ir a la playa mañana.', 1, 0, '''{"yo":"voy","tu":"vas","el":"va","nosotros":"vamos","vosotros":"vais","ellos":"van","gerundio":"yendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('otro/otra', 'another/other', 'adjective', 'Quiero otro trozo de pastel.', 1, 0, NULL, '[]'::jsonb),
  ('ese/esa', 'that', 'determiner', 'Ese perro es muy amigable.', 1, 0, NULL, '[]'::jsonb),
  ('la', 'the  / her/it', 'pronoun', 'La vi en el parque.', 1, 0, NULL, '["fem"]'::jsonb),
  ('si', 'if', 'conjunction', 'Si llueve, no saldremos.', 1, 0, NULL, '[]'::jsonb),
  ('me', 'to me/for me', 'pronoun', 'Me dio un regalo hermoso.', 1, 0, NULL, '[]'::jsonb),
  ('ya', 'already/now', 'adverb', 'Ya terminé mi trabajo.', 1, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('ver', 'to see', 'verb', 'Quiero ver esa película.', 1, 0, '''{"yo":"veo","tu":"ves","el":"ve","nosotros":"vemos","vosotros":"veis","ellos":"ven","gerundio":"viendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('porque', 'because', 'conjunction', 'No fui porque estaba enfermo.', 1, 0, NULL, '[]'::jsonb),
  ('dar', 'to give', 'verb', 'Te voy a dar un consejo.', 1, 0, '''{"yo":"doy","tu":"das","el":"da","nosotros":"damos","vosotros":"dais","ellos":"dan","gerundio":"dando"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('cuando', 'when', 'conjunction', 'Te llamaré cuando llegue.', 1, 0, NULL, '[]'::jsonb),
  ('muy', 'very', 'adverb', 'Estoy muy feliz hoy.', 1, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('sin', 'without', 'preposition', 'No puedo vivir sin ti.', 1, 0, NULL, '[]'::jsonb),
  ('vez', 'time/instance', 'noun', 'Es la primera vez que vengo aquí.', 1, 0, NULL, '[]'::jsonb),
  ('mucho', 'much/a lot', 'adjective', 'Hace mucho calor hoy.', 1, 0, NULL, '[]'::jsonb),
  ('saber', 'to know', 'verb', 'No sé la respuesta.', 1, 0, '''{"yo":"sé","tu":"sabes","el":"sabe","nosotros":"sabemos","vosotros":"sabéis","ellos":"saben","gerundio":"sabiendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('qué', 'what', 'pronoun', '¿Qué quieres comer?', 1, 0, NULL, '[]'::jsonb),
  ('sobre', 'on/over/about', 'preposition', 'El libro está sobre la mesa.', 1, 0, NULL, '[]'::jsonb),
  ('mi', 'my', 'determiner', 'Mi coche es azul.', 1, 0, NULL, '[]'::jsonb),
  ('al', 'to the', 'preposition', 'Voy al parque todos los días.', 1, 0, NULL, '["a + el"]'::jsonb),
  ('todo', 'all/every', 'adjective', 'Todo el mundo está aquí.', 1, 0, NULL, '[]'::jsonb),
  ('también', 'also/too', 'adverb', 'Yo también quiero un helado.', 1, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('hasta', 'until/even', 'preposition', 'Trabajo hasta las cinco.', 1, 0, NULL, '[]'::jsonb),
  ('hay', 'there is/there are', 'verb', 'Hay mucha gente en la fiesta.', 1, 0, '''null''::jsonb'::jsonb, '["from haber"]'::jsonb),
  ('año', 'year', 'noun', 'Feliz año nuevo.', 1, 0, NULL, '[]'::jsonb),
  ('dos', 'two', 'number', 'Tengo dos perros.', 1, 0, NULL, '[]'::jsonb),
  ('querer', 'to want/love', 'verb', 'Quiero un café, por favor.', 1, 0, '''{"yo":"quiero","tu":"quieres","el":"quiere","nosotros":"queremos","vosotros":"queréis","ellos":"quieren","gerundio":"queriendo"}''::jsonb'::jsonb, '["irregular e->ie"]'::jsonb),
  ('entre', 'between/among', 'preposition', 'El banco está entre la farmacia y el supermercado.', 1, 0, NULL, '[]'::jsonb),
  ('así', 'like this/so', 'adverb', 'Hazlo así, es más fácil.', 1, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('primero', 'first', 'adjective', 'Es mi primer día de trabajo.', 1, 0, NULL, '[]'::jsonb),
  ('desde', 'from/since', 'preposition', 'Vivo aquí desde 2010.', 1, 0, NULL, '[]'::jsonb),
  ('grande', 'big/large', 'adjective', 'Su casa es muy grande.', 1, 0, NULL, '[]'::jsonb),
  ('nos', 'us/to us', 'pronoun', 'Nos gusta ir a la playa.', 1, 0, NULL, '[]'::jsonb),
  ('llegar', 'to arrive', 'verb', 'El tren va a llegar pronto.', 1, 0, '''{"yo":"llego","tu":"llegas","el":"llega","nosotros":"llegamos","vosotros":"llegáis","ellos":"llegan","gerundio":"llegando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('pasar', 'to pass/happen/spend time', 'verb', '¿Qué pasa aquí?', 1, 0, '''{"yo":"paso","tu":"pasas","el":"pasa","nosotros":"pasamos","vosotros":"pasáis","ellos":"pasan","gerundio":"pasando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('sí', 'yes', 'adverb', 'Sí, quiero ir contigo.', 1, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('ni', 'nor/neither', 'conjunction', 'No quiero ni té ni café.', 1, 0, NULL, '[]'::jsonb),
  ('nosotros', 'we/us', 'pronoun', 'Nosotros somos estudiantes.', 1, 0, NULL, '[]'::jsonb),
  ('tiempo', 'time/weather', 'noun', 'No tengo mucho tiempo libre.', 1, 0, NULL, '[]'::jsonb),
  ('mismo', 'same', 'adjective', 'Tenemos el mismo problema.', 1, 0, NULL, '[]'::jsonb),
  ('bien', 'well/fine', 'adverb', 'Todo está muy bien.', 1, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('día', 'day', 'noun', '¡Buenos días!', 1, 0, NULL, '[]'::jsonb),
  ('donde', 'where', 'conjunction', '¿Dónde está el baño?', 1, 0, NULL, '[]'::jsonb),
  ('ahora', 'now', 'adverb', 'Tengo que irme ahora.', 1, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('poco', 'little/few', 'adjective', 'Tengo poco dinero en efectivo.', 1, 0, NULL, '[]'::jsonb),
  ('cada', 'each/every', 'adjective', 'Leo un libro cada mes.', 1, 0, NULL, '[]'::jsonb),
  ('vida', 'life', 'noun', 'La vida es hermosa.', 1, 0, NULL, '[]'::jsonb),
  ('entonces', 'then/so', 'adverb', 'Entonces, ¿qué hacemos?', 1, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('menos', 'less/fewer', 'adverb', 'Cuesta menos de diez euros.', 1, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('nuevo', 'new', 'adjective', 'Tengo un coche nuevo.', 1, 0, NULL, '[]'::jsonb),
  ('solo/solamente', 'only/just', 'adverb', 'Solo quiero un vaso de agua.', 1, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('tan', 'so/as', 'adverb', 'Es tan alto como su padre.', 1, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('cosa', 'thing', 'noun', '¿Qué es esa cosa?', 1, 0, NULL, '[]'::jsonb),
  ('parte', 'part/portion', 'noun', 'Leí la primera parte del libro.', 1, 0, NULL, '[]'::jsonb),
  ('después', 'after/later', 'adverb', 'Te llamaré después de la cena.', 1, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('alguno/algún', 'some/someone', 'adjective', '¿Tienes algún problema?', 1, 0, NULL, '[]'::jsonb),
  ('siempre', 'always', 'adverb', 'Siempre llego tarde.', 1, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('creer', 'to believe/think', 'verb', 'Creo que va a llover.', 1, 0, '''{"yo":"creo","tu":"crees","el":"cree","nosotros":"creemos","vosotros":"creéis","ellos":"creen","gerundio":"creyendo"}''::jsonb'::jsonb, '["regular -er"]'::jsonb),
  ('encontrar', 'to find', 'verb', 'No puedo encontrar mis llaves.', 1, 0, '''{"yo":"encuentro","tu":"encuentras","el":"encuentra","nosotros":"encontramos","vosotros":"encontráis","ellos":"encuentran","gerundio":"encontrando"}''::jsonb'::jsonb, '["irregular o->ue"]'::jsonb),
  ('forma', 'form/shape/way', 'noun', 'Esta es la mejor forma de hacerlo.', 1, 0, NULL, '[]'::jsonb),
  ('nada', 'nothing/anything', 'pronoun', 'No hay nada en la nevera.', 1, 0, NULL, '[]'::jsonb),
  ('hombre', 'man', 'noun', 'Ese hombre es mi tío.', 1, 0, NULL, '[]'::jsonb),
  ('bien', 'good/fine', 'adjective', 'Está bien.', 1, 0, NULL, '[]'::jsonb),
  ('mujer', 'woman', 'noun', 'Esa mujer es muy inteligente.', 1, 0, NULL, '[]'::jsonb),
  ('algo', 'something/anything', 'pronoun', 'Necesito algo para comer.', 1, 0, NULL, '[]'::jsonb),
  ('parecer', 'to seem/appear', 'verb', 'Me parece una buena idea.', 1, 0, '''{"yo":"pareco","tu":"pareces","el":"parece","nosotros":"parecemos","vosotros":"parecéis","ellos":"parecen","gerundio":"pareciendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('queda', 'remains/is located', 'verb', 'La tienda queda cerca de aquí.', 1, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('hablar', 'to talk/speak', 'verb', 'Quiero hablar contigo.', 2, 0, '''{"yo":"hablo","tu":"hablas","el":"habla","nosotros":"hablamos","vosotros":"habláis","ellos":"hablan","gerundio":"hablando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('tomar', 'to take/drink', 'verb', 'Voy a tomar un café.', 2, 0, '''{"yo":"tomo","tu":"tomas","el":"toma","nosotros":"tomamos","vosotros":"tomáis","ellos":"toman","gerundio":"tomando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('trabajar', 'to work', 'verb', 'Trabajo todos los días.', 2, 0, '''{"yo":"trabajo","tu":"trabajas","el":"trabaja","nosotros":"trabajamos","vosotros":"trabajáis","ellos":"trabajan","gerundio":"trabajando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('esperar', 'to wait/hope', 'verb', 'Espero que tengas un buen día.', 2, 0, '''{"yo":"espero","tu":"esperas","el":"espera","nosotros":"esperamos","vosotros":"esperáis","ellos":"esperan","gerundio":"esperando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('mirar', 'to look/watch', 'verb', 'Mira ese pájaro.', 2, 0, '''{"yo":"miro","tu":"miras","el":"mira","nosotros":"miramos","vosotros":"miráis","ellos":"miran","gerundio":"mirando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('comprar', 'to buy', 'verb', 'Quiero comprar un libro.', 2, 0, '''{"yo":"compro","tu":"compras","el":"compra","nosotros":"compramos","vosotros":"compráis","ellos":"compran","gerundio":"comprando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('necesitar', 'to need', 'verb', 'Necesito más tiempo.', 2, 0, '''{"yo":"necesito","tu":"necesitas","el":"necesita","nosotros":"necesitamos","vosotros":"necesitáis","ellos":"necesitan","gerundio":"necesitando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('terminar', 'to finish', 'verb', 'Ya terminé mi tarea.', 2, 0, '''{"yo":"termino","tu":"terminas","el":"termina","nosotros":"terminamos","vosotros":"termináis","ellos":"terminan","gerundio":"terminando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('explicar', 'to explain', 'verb', '¿Puedes explicar esto?', 2, 0, '''{"yo":"explico","tu":"explicas","el":"explica","nosotros":"explicamos","vosotros":"explicáis","ellos":"explican","gerundio":"explicando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('preguntar', 'to ask', 'verb', 'Quiero hacerte una pregunta.', 2, 0, '''{"yo":"pregunto","tu":"preguntas","el":"pregunta","nosotros":"preguntamos","vosotros":"preguntáis","ellos":"preguntan","gerundio":"preguntando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('estudiar', 'to study', 'verb', 'Estudio español en la escuela.', 2, 0, '''{"yo":"estudio","tu":"estudias","el":"estudia","nosotros":"estudiamos","vosotros":"estudiáis","ellos":"estudian","gerundio":"estudiando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('escuchar', 'to listen', 'verb', 'Escucha esta canción.', 2, 0, '''{"yo":"escucho","tu":"escuchas","el":"escucha","nosotros":"escuchamos","vosotros":"escucháis","ellos":"escuchan","gerundio":"escuchando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('viajar', 'to travel', 'verb', 'Me encanta viajar.', 2, 0, '''{"yo":"viajo","tu":"viajas","el":"viaja","nosotros":"viajamos","vosotros":"viajáis","ellos":"viajan","gerundio":"viajando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('llamar', 'to call', 'verb', 'Te voy a llamar mañana.', 2, 0, '''{"yo":"llamo","tu":"llamas","el":"llama","nosotros":"llamamos","vosotros":"llamáis","ellos":"llaman","gerundio":"llamando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('ayudar', 'to help', 'verb', '¿Me puedes ayudar?', 2, 0, '''{"yo":"ayudo","tu":"ayudas","el":"ayuda","nosotros":"ayudamos","vosotros":"ayudáis","ellos":"ayudan","gerundio":"ayudando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('enseñar', 'to teach/show', 'verb', 'Ella me va a enseñar a bailar.', 2, 0, '''{"yo":"enseño","tu":"enseñas","el":"enseña","nosotros":"enseñamos","vosotros":"enseñáis","ellos":"enseñan","gerundio":"enseñando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('ganar', 'to win/earn', 'verb', 'Nuestro equipo ganó el partido.', 2, 0, '''{"yo":"gano","tu":"ganas","el":"gana","nosotros":"ganamos","vosotros":"ganáis","ellos":"ganan","gerundio":"ganando"}''::jsonb'::jsonb, '["regular -ar"]'::jsonb),
  ('comer', 'to eat', 'verb', 'Me gusta comer pollo.', 2, 0, '''{"yo":"como","tu":"comes","el":"come","nosotros":"comemos","vosotros":"coméis","ellos":"comen","gerundio":"comiendo"}''::jsonb'::jsonb, '["regular -er"]'::jsonb),
  ('beber', 'to drink', 'verb', 'Vamos a beber unas cervezas.', 2, 0, '''{"yo":"bebo","tu":"bebes","el":"bebe","nosotros":"bebemos","vosotros":"bebéis","ellos":"beben","gerundio":"bebiendo"}''::jsonb'::jsonb, '["regular -er"]'::jsonb),
  ('comprender', 'to understand', 'verb', 'No comprendo.', 2, 0, '''{"yo":"comprendo","tu":"comprendes","el":"comprende","nosotros":"comprendemos","vosotros":"comprendéis","ellos":"comprenden","gerundio":"comprendiendo"}''::jsonb'::jsonb, '["regular -er"]'::jsonb),
  ('aprender', 'to learn', 'verb', 'Quiero aprender más español.', 2, 0, '''{"yo":"aprendo","tu":"aprendes","el":"aprende","nosotros":"aprendemos","vosotros":"aprendéis","ellos":"aprenden","gerundio":"aprendiendo"}''::jsonb'::jsonb, '["regular -er"]'::jsonb),
  ('vender', 'to sell', 'verb', 'Él vende coches usados.', 2, 0, '''{"yo":"vendo","tu":"vendes","el":"vende","nosotros":"vendemos","vosotros":"vendéis","ellos":"venden","gerundio":"vendiendo"}''::jsonb'::jsonb, '["regular -er"]'::jsonb),
  ('leer', 'to read', 'verb', 'Leo un libro cada semana.', 2, 0, '''{"yo":"leo","tu":"lees","el":"lee","nosotros":"leemos","vosotros":"leéis","ellos":"leen","gerundio":"leyendo"}''::jsonb'::jsonb, '["regular -er"]'::jsonb),
  ('correr', 'to run', 'verb', 'Corro en el parque todas las mañanas.', 2, 0, '''{"yo":"corro","tu":"corres","el":"corre","nosotros":"corremos","vosotros":"corréis","ellos":"corren","gerundio":"corriendo"}''::jsonb'::jsonb, '["regular -er"]'::jsonb),
  ('esconder', 'to hide', 'verb', 'No te escondas.', 2, 0, '''{"yo":"escondo","tu":"escondes","el":"esconde","nosotros":"escondemos","vosotros":"escondéis","ellos":"esconden","gerundio":"escondiendo"}''::jsonb'::jsonb, '["regular -er"]'::jsonb),
  ('prometer', 'to promise', 'verb', 'Te prometo que iré.', 2, 0, '''{"yo":"prometo","tu":"prometes","el":"promete","nosotros":"prometemos","vosotros":"prometéis","ellos":"prometen","gerundio":"prometiendo"}''::jsonb'::jsonb, '["regular -er"]'::jsonb),
  ('romper', 'to break', 'verb', '¡No rompas el vaso!', 2, 0, '''{"yo":"rompo","tu":"rompes","el":"rompe","nosotros":"rompemos","vosotros":"rompéis","ellos":"rompen","gerundio":"rompiendo"}''::jsonb'::jsonb, '["regular -er, irreg part"]'::jsonb),
  ('responder', 'to answer', 'verb', 'Responde a mi pregunta.', 2, 0, '''{"yo":"respondo","tu":"respondes","el":"responde","nosotros":"respondemos","vosotros":"respondéis","ellos":"responden","gerundio":"respondiendo"}''::jsonb'::jsonb, '["regular -er"]'::jsonb),
  ('creer', 'to believe/think', 'verb', 'Creo en ti.', 2, 0, '''{"yo":"creo","tu":"crees","el":"cree","nosotros":"creemos","vosotros":"creéis","ellos":"creen","gerundio":"creyendo"}''::jsonb'::jsonb, '["regular -er"]'::jsonb),
  ('vivir', 'to live', 'verb', 'Vivo en Barcelona.', 2, 0, '''{"yo":"vivo","tu":"vives","el":"vive","nosotros":"vivimos","vosotros":"vivís","ellos":"viven","gerundio":"viviendo"}''::jsonb'::jsonb, '["regular -ir"]'::jsonb),
  ('escribir', 'to write', 'verb', 'Ella escribe poemas.', 2, 0, '''{"yo":"escribo","tu":"escribes","el":"escribe","nosotros":"escribimos","vosotros":"escribís","ellos":"escriben","gerundio":"escribiendo"}''::jsonb'::jsonb, '["regular -ir, irreg part"]'::jsonb),
  ('abrir', 'to open', 'verb', 'Abre la ventana, por favor.', 2, 0, '''{"yo":"abro","tu":"abres","el":"abre","nosotros":"abrimos","vosotros":"abrís","ellos":"abren","gerundio":"abriendo"}''::jsonb'::jsonb, '["regular -ir, irreg part"]'::jsonb),
  ('recibir', 'to receive', 'verb', 'Recibí tu carta.', 2, 0, '''{"yo":"recibo","tu":"recibes","el":"recibe","nosotros":"recibimos","vosotros":"recibís","ellos":"reciben","gerundio":"recibiendo"}''::jsonb'::jsonb, '["regular -ir"]'::jsonb),
  ('decidir', 'to decide', 'verb', 'Tienes que decidir pronto.', 2, 0, '''{"yo":"decido","tu":"decides","el":"decide","nosotros":"decidimos","vosotros":"decidís","ellos":"deciden","gerundio":"decidiendo"}''::jsonb'::jsonb, '["regular -ir"]'::jsonb),
  ('subir', 'to go up/climb', 'verb', 'Sube las escaleras.', 2, 0, '''{"yo":"subo","tu":"subes","el":"sube","nosotros":"subimos","vosotros":"subís","ellos":"suben","gerundio":"subiendo"}''::jsonb'::jsonb, '["regular -ir"]'::jsonb),
  ('sufrir', 'to suffer', 'verb', 'No quiero sufrir más.', 2, 0, '''{"yo":"sufro","tu":"sufres","el":"sufre","nosotros":"sufrimos","vosotros":"sufrís","ellos":"sufren","gerundio":"sufriendo"}''::jsonb'::jsonb, '["regular -ir"]'::jsonb),
  ('ocurrir', 'to happen/occur', 'verb', 'Ese accidente ocurrió ayer.', 2, 0, '''{"yo":"ocurro","tu":"ocurres","el":"ocurre","nosotros":"ocurrimos","vosotros":"ocurrís","ellos":"ocurren","gerundio":"ocurriendo"}''::jsonb'::jsonb, '["regular -ir"]'::jsonb),
  ('añadir', 'to add', 'verb', 'Añade un poco de sal.', 2, 0, '''{"yo":"añado","tu":"añades","el":"añade","nosotros":"añadimos","vosotros":"añadís","ellos":"añaden","gerundio":"añadiendo"}''::jsonb'::jsonb, '["regular -ir"]'::jsonb),
  ('ser', 'to be', 'verb', 'Mi padre es alto.', 3, 0, '''{"yo":"soy","tu":"eres","el":"es","nosotros":"somos","vosotros":"sois","ellos":"son","gerundio":"siendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('estar', 'to be', 'verb', 'Estoy en casa.', 3, 0, '''{"yo":"estoy","tu":"estás","el":"está","nosotros":"estamos","vosotros":"estáis","ellos":"están","gerundio":"estando"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('tener', 'to have', 'verb', 'Tengo dos hermanos.', 3, 0, '''{"yo":"tengo","tu":"tienes","el":"tiene","nosotros":"tenemos","vosotros":"tenéis","ellos":"tienen","gerundio":"teniendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('hacer', 'to do/to make', 'verb', '¿Qué estás haciendo?', 3, 0, '''{"yo":"hago","tu":"haces","el":"hace","nosotros":"hacemos","vosotros":"hacéis","ellos":"hacen","gerundio":"haciendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('poder', 'to be able to/can', 'verb', '¿Puedes ayudarme?', 3, 0, '''{"yo":"puedo","tu":"puedes","el":"puede","nosotros":"podemos","vosotros":"podéis","ellos":"pueden","gerundio":"pudiendo"}''::jsonb'::jsonb, '["irregular o->ue"]'::jsonb),
  ('decir', 'to say/to tell', 'verb', 'Dime la verdad.', 3, 0, '''{"yo":"digo","tu":"dices","el":"dice","nosotros":"decimos","vosotros":"decís","ellos":"dicen","gerundio":"diciendo"}''::jsonb'::jsonb, '["irregular e->i"]'::jsonb),
  ('ir', 'to go', 'verb', 'Vamos al cine esta noche.', 3, 0, '''{"yo":"voy","tu":"vas","el":"va","nosotros":"vamos","vosotros":"vais","ellos":"van","gerundio":"yendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('ver', 'to see', 'verb', 'Quiero ver la televisión.', 3, 0, '''{"yo":"veo","tu":"ves","el":"ve","nosotros":"vemos","vosotros":"veis","ellos":"ven","gerundio":"viendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('dar', 'to give', 'verb', 'Te doy mi palabra.', 3, 0, '''{"yo":"doy","tu":"das","el":"da","nosotros":"damos","vosotros":"dais","ellos":"dan","gerundio":"dando"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('saber', 'to know facts/how to', 'verb', 'Lo sé todo.', 3, 0, '''{"yo":"sé","tu":"sabes","el":"sabe","nosotros":"sabemos","vosotros":"sabéis","ellos":"saben","gerundio":"sabiendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('querer', 'to want/to love', 'verb', 'Te quiero mucho.', 3, 0, '''{"yo":"quiero","tu":"quieres","el":"quiere","nosotros":"queremos","vosotros":"queréis","ellos":"quieren","gerundio":"queriendo"}''::jsonb'::jsonb, '["irregular e->ie"]'::jsonb),
  ('pensar', 'to think', 'verb', 'Pienso que es una buena idea.', 3, 0, '''{"yo":"pienso","tu":"piensas","el":"piensa","nosotros":"pensamos","vosotros":"pensáis","ellos":"piensan","gerundio":"pensando"}''::jsonb'::jsonb, '["irregular e->ie"]'::jsonb),
  ('encontrar', 'to find', 'verb', 'No la encuentro.', 3, 0, '''{"yo":"encuentro","tu":"encuentras","el":"encuentra","nosotros":"encontramos","vosotros":"encontráis","ellos":"encuentran","gerundio":"encontrando"}''::jsonb'::jsonb, '["irregular o->ue"]'::jsonb),
  ('volver', 'to return/go back', 'verb', 'Vuelvo a las seis.', 3, 0, '''{"yo":"vuelvo","tu":"vuelves","el":"vuelve","nosotros":"volvemos","vosotros":"volvéis","ellos":"vuelven","gerundio":"volviendo"}''::jsonb'::jsonb, '["irregular o->ue"]'::jsonb),
  ('salir', 'to leave/go out', 'verb', 'Salgo con mis amigos.', 3, 0, '''{"yo":"salgo","tu":"sales","el":"sale","nosotros":"salimos","vosotros":"salís","ellos":"salen","gerundio":"saliendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('conocer', 'to know people/places', 'verb', 'Conozco bien esa ciudad.', 3, 0, '''{"yo":"conozco","tu":"conoces","el":"conoce","nosotros":"conocemos","vosotros":"conocéis","ellos":"conocen","gerundio":"conociendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('empezar', 'to begin/start', 'verb', 'La película empieza ahora.', 3, 0, '''{"yo":"empiezo","tu":"empiezas","el":"empieza","nosotros":"empezamos","vosotros":"empezáis","ellos":"empiezan","gerundio":"empezando"}''::jsonb'::jsonb, '["irregular e->ie"]'::jsonb),
  ('entender', 'to understand', 'verb', 'No entiendo el problema.', 3, 0, '''{"yo":"entiendo","tu":"entiendes","el":"entiende","nosotros":"entendemos","vosotros":"entendéis","ellos":"entienden","gerundio":"entendiendo"}''::jsonb'::jsonb, '["irregular e->ie"]'::jsonb),
  ('pedir', 'to ask for/request', 'verb', 'Voy a pedir una pizza.', 3, 0, '''{"yo":"pido","tu":"pides","el":"pide","nosotros":"pedimos","vosotros":"pedís","ellos":"piden","gerundio":"pidiendo"}''::jsonb'::jsonb, '["irregular e->i"]'::jsonb),
  ('sentir', 'to feel/regret', 'verb', 'Lo siento mucho.', 3, 0, '''{"yo":"siento","tu":"sientes","el":"siente","nosotros":"sentimos","vosotros":"sentís","ellos":"sienten","gerundio":"sintiendo"}''::jsonb'::jsonb, '["irregular e->ie"]'::jsonb),
  ('dormir', 'to sleep', 'verb', 'Quiero dormir ahora.', 3, 0, '''{"yo":"duermo","tu":"duermes","el":"duerme","nosotros":"dormimos","vosotros":"dormís","ellos":"duermen","gerundio":"durmiendo"}''::jsonb'::jsonb, '["irregular o->ue"]'::jsonb),
  ('seguir', 'to follow/continue', 'verb', 'Sígueme, por favor.', 3, 0, '''{"yo":"sigo","tu":"sigues","el":"sigue","nosotros":"seguimos","vosotros":"seguís","ellos":"siguen","gerundio":"siguiendo"}''::jsonb'::jsonb, '["irregular e->i"]'::jsonb),
  ('venir', 'to come', 'verb', 'Ven aquí.', 3, 0, '''{"yo":"vengo","tu":"vienes","el":"viene","nosotros":"venimos","vosotros":"venís","ellos":"vienen","gerundio":"viniendo"}''::jsonb'::jsonb, '["irregular e->ie"]'::jsonb),
  ('traer', 'to bring', 'verb', '¿Me traes un vaso de agua?', 3, 0, '''{"yo":"traigo","tu":"traes","el":"trae","nosotros":"traemos","vosotros":"traéis","ellos":"traen","gerundio":"trayendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('poner', 'to put/place', 'verb', 'Pon el libro en la mesa.', 3, 0, '''{"yo":"pongo","tu":"pones","el":"pone","nosotros":"ponemos","vosotros":"ponéis","ellos":"ponen","gerundio":"poniendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('jugar', 'to play', 'verb', 'Jugamos al fútbol los domingos.', 3, 0, '''{"yo":"juego","tu":"juegas","el":"juega","nosotros":"jugamos","vosotros":"jugáis","ellos":"juegan","gerundio":"jugando"}''::jsonb'::jsonb, '["irregular u->ue"]'::jsonb),
  ('cerrar', 'to close', 'verb', 'Cierra la puerta.', 3, 0, '''{"yo":"cierro","tu":"cierras","el":"cierra","nosotros":"cerramos","vosotros":"cerráis","ellos":"cierran","gerundio":"cerrando"}''::jsonb'::jsonb, '["irregular e->ie"]'::jsonb),
  ('recordar', 'to remember/remind', 'verb', 'Recuerdo tu cara.', 3, 0, '''{"yo":"recuerdo","tu":"recuerdas","el":"recuerda","nosotros":"recordamos","vosotros":"recordáis","ellos":"recuerdan","gerundio":"recordando"}''::jsonb'::jsonb, '["irregular o->ue"]'::jsonb),
  ('mostrar', 'to show', 'verb', 'Enséñame tu nuevo coche.', 3, 0, '''{"yo":"muestro","tu":"muestras","el":"muestra","nosotros":"mostramos","vosotros":"mostráis","ellos":"muestran","gerundio":"mostrando"}''::jsonb'::jsonb, '["irregular o->ue"]'::jsonb),
  ('perder', 'to lose/miss', 'verb', 'No quiero perderte.', 3, 0, '''{"yo":"pierdo","tu":"pierdes","el":"pierde","nosotros":"perdemos","vosotros":"perdéis","ellos":"pierden","gerundio":"perdiendo"}''::jsonb'::jsonb, '["irregular e->ie"]'::jsonb),
  ('caer', 'to fall', 'verb', 'Las hojas caen en otoño.', 3, 0, '''{"yo":"caigo","tu":"caes","el":"cae","nosotros":"caemos","vosotros":"caéis","ellos":"caen","gerundio":"cayendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('oír', 'to hear/listen', 'verb', 'No te oigo bien.', 3, 0, '''{"yo":"oigo","tu":"oyes","el":"oye","nosotros":"oímos","vosotros":"oís","ellos":"oyen","gerundio":"oyendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('conseguir', 'to get/obtain', 'verb', 'Consiguió un nuevo trabajo.', 3, 0, '''{"yo":"consigo","tu":"consigues","el":"consigue","nosotros":"conseguimos","vosotros":"conseguís","ellos":"consiguen","gerundio":"consiguiendo"}''::jsonb'::jsonb, '["irregular e->i"]'::jsonb),
  ('servir', 'to serve', 'verb', 'Esta herramienta no sirve.', 3, 0, '''{"yo":"sirvo","tu":"sirves","el":"sirve","nosotros":"servimos","vosotros":"servís","ellos":"sirven","gerundio":"sirviendo"}''::jsonb'::jsonb, '["irregular e->i"]'::jsonb),
  ('repetir', 'to repeat', 'verb', 'Por favor, repita la pregunta.', 3, 0, '''{"yo":"repito","tu":"repites","el":"repite","nosotros":"repetimos","vosotros":"repetís","ellos":"repiten","gerundio":"repitiendo"}''::jsonb'::jsonb, '["irregular e->i"]'::jsonb),
  ('reír', 'to laugh', 'verb', 'Me hace reír.', 3, 0, '''{"yo":"río","tu":"ríes","el":"ríe","nosotros":"reímos","vosotros":"reís","ellos":"ríen","gerundio":"riendo"}''::jsonb'::jsonb, '["irregular e->i"]'::jsonb),
  ('costar', 'to cost', 'verb', '¿Cuánto cuesta este coche?', 3, 0, '''{"yo":"cuesto","tu":"cuestas","el":"cuesta","nosotros":"costamos","vosotros":"costáis","ellos":"cuestan","gerundio":"costando"}''::jsonb'::jsonb, '["irregular o->ue"]'::jsonb),
  ('medir', 'to measure', 'verb', 'Mide dos metros de altura.', 3, 0, '''{"yo":"mido","tu":"mides","el":"mide","nosotros":"medimos","vosotros":"medís","ellos":"miden","gerundio":"midiendo"}''::jsonb'::jsonb, '["irregular e->i"]'::jsonb),
  ('bueno/buen', 'good', 'adjective', 'Es un buen perro.', 4, 0, NULL, '[]'::jsonb),
  ('malo/mal', 'bad', 'adjective', 'Hace mal tiempo.', 4, 0, NULL, '[]'::jsonb),
  ('grande/gran', 'big', 'adjective', 'Es un gran problema.', 4, 0, NULL, '[]'::jsonb),
  ('pequeño', 'small', 'adjective', 'Este coche es muy pequeño.', 4, 0, NULL, '[]'::jsonb),
  ('nuevo', 'new', 'adjective', 'Mi coche es nuevo.', 4, 0, NULL, '[]'::jsonb),
  ('viejo', 'old', 'adjective', 'Tengo un coche viejo.', 4, 0, NULL, '[]'::jsonb),
  ('alto', 'tall/high', 'adjective', 'Mi hermano es muy alto.', 4, 0, NULL, '[]'::jsonb),
  ('bajo', 'short/low', 'adjective', 'El techo es muy bajo.', 4, 0, NULL, '[]'::jsonb),
  ('largo', 'long', 'adjective', 'El camino es largo.', 4, 0, NULL, '[]'::jsonb),
  ('corto', 'short', 'adjective', 'El pelo de Juan es corto.', 4, 0, NULL, '["length"]'::jsonb),
  ('fácil', 'easy', 'adjective', 'El examen fue muy fácil.', 4, 0, NULL, '[]'::jsonb),
  ('difícil', 'hard/difficult', 'adjective', 'Aprender chino es difícil.', 4, 0, NULL, '[]'::jsonb),
  ('feliz', 'happy', 'adjective', 'Estoy muy feliz hoy.', 4, 0, NULL, '[]'::jsonb),
  ('triste', 'sad', 'adjective', 'La película fue muy triste.', 4, 0, NULL, '[]'::jsonb),
  ('rápido', 'fast/quick', 'adjective', 'Corre muy rápido.', 4, 0, NULL, '[]'::jsonb),
  ('lento', 'slow', 'adjective', 'Esta tortuga es lenta.', 4, 0, NULL, '[]'::jsonb),
  ('caliente', 'hot', 'adjective', 'El café está muy caliente.', 4, 0, NULL, '[]'::jsonb),
  ('frío', 'cold', 'adjective', 'Hace mucho frío hoy.', 4, 0, NULL, '[]'::jsonb),
  ('bonito', 'pretty/beautiful', 'adjective', 'Qué vestido tan bonito.', 4, 0, NULL, '[]'::jsonb),
  ('feo', 'ugly', 'adjective', 'Ese edificio es muy feo.', 4, 0, NULL, '[]'::jsonb),
  ('caro', 'expensive', 'adjective', 'Ese coche es demasiado caro.', 4, 0, NULL, '[]'::jsonb),
  ('barato', 'cheap', 'adjective', 'Compré esto muy barato.', 4, 0, NULL, '[]'::jsonb),
  ('rico', 'rich/delicious', 'adjective', 'La comida está muy rica.', 4, 0, NULL, '[]'::jsonb),
  ('pobre', 'poor', 'adjective', 'Ellos son de una familia pobre.', 4, 0, NULL, '[]'::jsonb),
  ('fuerte', 'strong', 'adjective', 'Él es muy fuerte.', 4, 0, NULL, '[]'::jsonb),
  ('débil', 'weak', 'adjective', 'Me siento un poco débil.', 4, 0, NULL, '[]'::jsonb),
  ('joven', 'young', 'adjective', 'Es demasiado joven para conducir.', 4, 0, NULL, '[]'::jsonb),
  ('mayor', 'older/larger', 'adjective', 'Mi hermano mayor vive en Madrid.', 4, 0, NULL, '[]'::jsonb),
  ('mejor', 'better/best', 'adjective', 'Él es mi mejor amigo.', 4, 0, NULL, '[]'::jsonb),
  ('peor', 'worse/worst', 'adjective', 'Fue el peor día de mi vida.', 4, 0, NULL, '[]'::jsonb),
  ('aquí', 'here', 'adverb', 'Ven aquí, por favor.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('allí/allá', 'there', 'adverb', 'Mi casa está allí.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('cerca', 'close/near', 'adverb', 'Vivo cerca de la escuela.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('lejos', 'far', 'adverb', 'El supermercado está lejos.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('antes', 'before', 'adverb', 'Tienes que terminar antes de mañana.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('después', 'after/afterward', 'adverb', 'Vamos a comer después.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('siempre', 'always', 'adverb', 'Siempre me levanto temprano.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('nunca', 'never', 'adverb', 'Nunca he estado en España.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('pronto', 'soon', 'adverb', 'Te veré muy pronto.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('tarde', 'late/afternoon', 'adverb', 'Llegué demasiado tarde al tren.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('temprano', 'early', 'adverb', 'Mañana me levantaré temprano.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('mucho', 'much/a lot/very', 'adverb', 'Trabajo mucho todos los días.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('poco', 'little/not much', 'adverb', 'Queda poco tiempo.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('bastante', 'enough/quite', 'adverb', 'Es bastante inteligente.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('demasiado', 'too much/too', 'adverb', 'Comí demasiado pastel.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('solo/solamente', 'only/just', 'adverb', 'Solo quiero un café.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('todavía/aún', 'still/yet', 'adverb', 'Todavía no he terminado.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('ya', 'already/now/yet', 'adverb', 'Ya son las diez y media.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('también', 'also/too', 'adverb', 'Yo también hablo inglés.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('tampoco', 'neither/not either', 'adverb', 'Él no sabe, y yo tampoco.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('así', 'like this/so/thus', 'adverb', 'Lo hice así.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('bien', 'well', 'adverb', 'Cantas muy bien.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('mal', 'badly/poorly', 'adverb', 'El coche funciona mal.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('quizás/tal vez', 'maybe/perhaps', 'adverb', 'Quizás llueva mañana.', 4, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('seguro', 'sure/safe', 'adjective', 'Estoy seguro de que vendrá.', 4, 0, NULL, '[]'::jsonb),
  ('uno', 'one', 'number', 'Solo quiero un helado.', 5, 0, NULL, '[]'::jsonb),
  ('dos', 'two', 'number', 'Tengo dos hermanos.', 5, 0, NULL, '[]'::jsonb),
  ('tres', 'three', 'number', 'Hay tres libros en la mesa.', 5, 0, NULL, '[]'::jsonb),
  ('cuatro', 'four', 'number', 'Las cuatro de la tarde.', 5, 0, NULL, '[]'::jsonb),
  ('cinco', 'five', 'number', 'Cinco minutos más.', 5, 0, NULL, '[]'::jsonb),
  ('seis', 'six', 'number', 'Seis personas vinieron a la cena.', 5, 0, NULL, '[]'::jsonb),
  ('siete', 'seven', 'number', 'Trabajo los siete días de la semana.', 5, 0, NULL, '[]'::jsonb),
  ('ocho', 'eight', 'number', 'Duermo ocho horas diarias.', 5, 0, NULL, '[]'::jsonb),
  ('nueve', 'nine', 'number', 'Nueve de cada diez dentistas lo recomiendan.', 5, 0, NULL, '[]'::jsonb),
  ('diez', 'ten', 'number', 'Diez euros, por favor.', 5, 0, NULL, '[]'::jsonb),
  ('veinte', 'twenty', 'number', 'Cuesta veinte dólares.', 5, 0, NULL, '[]'::jsonb),
  ('treinta', 'thirty', 'number', 'Tengo treinta años.', 5, 0, NULL, '[]'::jsonb),
  ('cuarenta', 'forty', 'number', 'Somos cuarenta en la clase.', 5, 0, NULL, '[]'::jsonb),
  ('cincuenta', 'fifty', 'number', 'El abrigo cuesta cincuenta euros.', 5, 0, NULL, '[]'::jsonb),
  ('cien', 'hundred', 'number', 'Más de cien personas asistieron.', 5, 0, NULL, '[]'::jsonb),
  ('primero', 'first', 'adjective', 'Mi primera lección.', 5, 0, NULL, '[]'::jsonb),
  ('segundo', 'second', 'adjective', 'El segundo piso.', 5, 0, NULL, '[]'::jsonb),
  ('tercero', 'third', 'adjective', 'Vive en el tercer piso.', 5, 0, NULL, '[]'::jsonb),
  ('lunes', 'Monday', 'noun', 'Nos vemos el lunes.', 5, 0, NULL, '[]'::jsonb),
  ('martes', 'Tuesday', 'noun', 'El martes tengo una reunión.', 5, 0, NULL, '[]'::jsonb),
  ('miércoles', 'Wednesday', 'noun', 'El miércoles es mi cumpleaños.', 5, 0, NULL, '[]'::jsonb),
  ('jueves', 'Thursday', 'noun', 'Salimos este jueves.', 5, 0, NULL, '[]'::jsonb),
  ('viernes', 'Friday', 'noun', 'Por fin es viernes.', 5, 0, NULL, '[]'::jsonb),
  ('sábado', 'Saturday', 'noun', 'El sábado vamos a la playa.', 5, 0, NULL, '[]'::jsonb),
  ('domingo', 'Sunday', 'noun', 'Los domingos descanso.', 5, 0, NULL, '[]'::jsonb),
  ('enero', 'January', 'noun', 'Hace frío en enero.', 5, 0, NULL, '[]'::jsonb),
  ('febrero', 'February', 'noun', 'Mi cumpleaños es en febrero.', 5, 0, NULL, '[]'::jsonb),
  ('marzo', 'March', 'noun', 'La primavera empieza en marzo.', 5, 0, NULL, '[]'::jsonb),
  ('abril', 'April', 'noun', 'Lluvias de abril.', 5, 0, NULL, '[]'::jsonb),
  ('mayo', 'May', 'noun', 'Mi madre nació en mayo.', 5, 0, NULL, '[]'::jsonb),
  ('junio', 'June', 'noun', 'Terminamos las clases en junio.', 5, 0, NULL, '[]'::jsonb),
  ('julio', 'July', 'noun', 'Nos vamos de vacaciones en julio.', 5, 0, NULL, '[]'::jsonb),
  ('agosto', 'August', 'noun', 'Hace mucho calor en agosto.', 5, 0, NULL, '[]'::jsonb),
  ('septiembre', 'September', 'noun', 'En septiembre vuelvo al trabajo.', 5, 0, NULL, '[]'::jsonb),
  ('octubre', 'October', 'noun', 'Halloween es en octubre.', 5, 0, NULL, '[]'::jsonb),
  ('noviembre', 'November', 'noun', 'Noviembre es un mes frío.', 5, 0, NULL, '[]'::jsonb),
  ('diciembre', 'December', 'noun', 'Navidad es en diciembre.', 5, 0, NULL, '[]'::jsonb),
  ('hoy', 'today', 'adverb', 'Hoy es un buen día.', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('ayer', 'yesterday', 'adverb', 'Ayer llovió mucho.', 5, 0, '''{"yo":"ayo","tu":"ayes","el":"aye","nosotros":"ayemos","vosotros":"ayéis","ellos":"ayen","gerundio":"ayiendo"}''::jsonb'::jsonb, '[]'::jsonb),
  ('mañana', 'tomorrow/morning', 'noun', 'Mañana será otro día.', 5, 0, NULL, '[]'::jsonb),
  ('noche', 'night', 'noun', 'Buenas noches.', 5, 0, NULL, '[]'::jsonb),
  ('tarde', 'afternoon', 'noun', 'Buenas tardes.', 5, 0, NULL, '[]'::jsonb),
  ('semana', 'week', 'noun', 'Nos vemos la próxima semana.', 5, 0, NULL, '[]'::jsonb),
  ('mes', 'month', 'noun', 'El próximo mes viajo a España.', 5, 0, NULL, '[]'::jsonb),
  ('año', 'year', 'noun', 'Feliz año nuevo.', 5, 0, NULL, '[]'::jsonb),
  ('hora', 'hour', 'noun', 'Tienes una hora para terminar.', 5, 0, NULL, '[]'::jsonb),
  ('minuto', 'minute', 'noun', 'Dame un minuto.', 5, 0, NULL, '[]'::jsonb),
  ('segundo', 'second', 'noun', 'Espera un segundo.', 5, 0, NULL, '[]'::jsonb),
  ('reloj', 'clock/watch', 'noun', 'Mi reloj está roto.', 5, 0, NULL, '[]'::jsonb),
  ('vez', 'time/instance', 'noun', 'Es la primera vez que vengo.', 5, 0, NULL, '[]'::jsonb),
  ('siempre', 'always', 'adverb', 'Siempre llego a tiempo.', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('nunca', 'never', 'adverb', 'Nunca bebo alcohol.', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('próximo', 'next', 'adjective', 'El próximo tren sale a las seis.', 5, 0, NULL, '[]'::jsonb),
  ('pasado', 'past/last', 'adjective', 'El fin de semana pasado estuve enfermo.', 5, 0, NULL, '[]'::jsonb),
  ('ahora', 'now', 'adverb', 'Tienes que venir ahora.', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('ya', 'already/now', 'adverb', 'Ya son las diez.', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('todavía', 'still/yet', 'adverb', 'Todavía estoy trabajando.', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('hombre', 'man', 'noun', 'Ese hombre es muy alto.', 6, 0, NULL, '[]'::jsonb),
  ('mujer', 'woman', 'noun', 'Aquella mujer es mi profesora.', 6, 0, NULL, '[]'::jsonb),
  ('niño/niña', 'boy/girl', 'noun', 'Los niños juegan en el parque.', 6, 0, NULL, '[]'::jsonb),
  ('padre', 'father', 'noun', 'Mi padre es médico.', 6, 0, NULL, '[]'::jsonb),
  ('madre', 'mother', 'noun', 'Mi madre cocina muy bien.', 6, 0, NULL, '[]'::jsonb),
  ('hermano/hermana', 'brother/sister', 'noun', 'Tengo un hermano menor.', 6, 0, NULL, '[]'::jsonb),
  ('hijo/hija', 'son/daughter', 'noun', 'Ellas son mis hijas.', 6, 0, NULL, '[]'::jsonb),
  ('abuelo/abuela', 'grandfather/grandmother', 'noun', 'Mis abuelos viven en el campo.', 6, 0, NULL, '[]'::jsonb),
  ('tío/tía', 'uncle/aunt', 'noun', 'Mi tía me compró un regalo.', 6, 0, NULL, '[]'::jsonb),
  ('pronto/prima', 'cousin', 'noun', 'Mis primos vienen esta tarde.', 6, 0, NULL, '[]'::jsonb),
  ('amigo/amiga', 'friend', 'noun', 'Él es mi mejor amigo.', 6, 0, NULL, '[]'::jsonb),
  ('novio/novia', 'boyfriend/girlfriend', 'noun', 'Ella es mi novia.', 6, 0, NULL, '[]'::jsonb),
  ('esposo/esposa', 'husband/wife', 'noun', 'Su esposo trabaja en un banco.', 6, 0, NULL, '[]'::jsonb),
  ('familia', 'family', 'noun', 'Mi familia es muy grande.', 6, 0, NULL, '[]'::jsonb),
  ('persona', 'person', 'noun', 'Ella es una buena persona.', 6, 0, NULL, '[]'::jsonb),
  ('gente', 'people', 'noun', 'Hay mucha gente en la calle.', 6, 0, NULL, '[]'::jsonb),
  ('señor/señora', 'Mr./Mrs.', 'noun', 'El señor García está aquí.', 6, 0, NULL, '[]'::jsonb),
  ('casa', 'house/home', 'noun', 'Vivo en una casa blanca.', 6, 0, NULL, '[]'::jsonb),
  ('apartamento', 'apartment', 'noun', 'Mi apartamento es pequeño.', 6, 0, NULL, '[]'::jsonb),
  ('habitación', 'room/bedroom', 'noun', 'Mi habitación está limpia.', 6, 0, NULL, '[]'::jsonb),
  ('baño', 'bathroom', 'noun', '¿Dónde está el baño?', 6, 0, NULL, '[]'::jsonb),
  ('cocina', 'kitchen', 'noun', 'La cocina huele muy bien.', 6, 0, NULL, '[]'::jsonb),
  ('sala', 'living room', 'noun', 'Vemos la televisión en la sala.', 6, 0, NULL, '[]'::jsonb),
  ('puerta', 'door', 'noun', 'Cierra la puerta, por favor.', 6, 0, NULL, '[]'::jsonb),
  ('ventana', 'window', 'noun', 'Abre la ventana, hace calor.', 6, 0, NULL, '[]'::jsonb),
  ('mesa', 'table', 'noun', 'La comida está en la mesa.', 6, 0, NULL, '[]'::jsonb),
  ('silla', 'chair', 'noun', 'Por favor, siéntate en esta silla.', 6, 0, NULL, '[]'::jsonb),
  ('cama', 'bed', 'noun', 'Estoy cansado, me voy a la cama.', 6, 0, NULL, '[]'::jsonb),
  ('mueble', 'piece of furniture', 'noun', 'Necesitamos muebles nuevos.', 6, 0, NULL, '[]'::jsonb),
  ('televisión', 'television', 'noun', 'Están viendo la televisión.', 6, 0, NULL, '[]'::jsonb),
  ('radio', 'radio', 'noun', 'Me gusta escuchar la radio.', 6, 0, NULL, '[]'::jsonb),
  ('teléfono', 'phone/telephone', 'noun', 'Sonó el teléfono.', 6, 0, NULL, '[]'::jsonb),
  ('ropa', 'clothes/clothing', 'noun', 'Tengo que comprar ropa nueva.', 6, 0, NULL, '[]'::jsonb),
  ('camisa', 'shirt', 'noun', 'Llevo una camisa azul.', 6, 0, NULL, '[]'::jsonb),
  ('pantalones', 'pants/trousers', 'noun', 'Estos pantalones son muy grandes.', 6, 0, NULL, '[]'::jsonb),
  ('zapato', 'shoe', 'noun', 'Me gustan tus zapatos nuevos.', 6, 0, NULL, '[]'::jsonb),
  ('vestido', 'dress', 'noun', 'Lleva un vestido rojo.', 6, 0, NULL, '[]'::jsonb),
  ('abrigo', 'coat', 'noun', 'Ponte el abrigo, hace frío.', 6, 0, NULL, '[]'::jsonb),
  ('sombrero', 'hat', 'noun', 'Me gusta tu sombrero.', 6, 0, NULL, '[]'::jsonb),
  ('gafas', 'glasses', 'noun', 'No puedo ver sin mis gafas.', 6, 0, NULL, '[]'::jsonb),
  ('agua', 'water', 'noun', 'Un vaso de agua, por favor.', 7, 0, NULL, '[]'::jsonb),
  ('comida', 'food/meal', 'noun', 'La comida está servida.', 7, 0, NULL, '[]'::jsonb),
  ('pan', 'bread', 'noun', 'Necesito comprar pan.', 7, 0, NULL, '[]'::jsonb),
  ('carne', 'meat', 'noun', 'No como carne, soy vegetariano.', 7, 0, NULL, '[]'::jsonb),
  ('pescado', 'fish', 'noun', 'Hoy cenamos pescado.', 7, 0, NULL, '[]'::jsonb),
  ('pollo', 'chicken', 'noun', 'El pollo asado huele bien.', 7, 0, NULL, '[]'::jsonb),
  ('queso', 'cheese', 'noun', 'Me encantan los macarrones con queso.', 7, 0, NULL, '[]'::jsonb),
  ('huevo', 'egg', 'noun', 'Desayuno dos huevos todos los días.', 7, 0, NULL, '[]'::jsonb),
  ('fruta', 'fruit', 'noun', 'Debes comer más fruta.', 7, 0, NULL, '[]'::jsonb),
  ('manzana', 'apple', 'noun', 'Una manzana al día.', 7, 0, NULL, '[]'::jsonb),
  ('naranja', 'orange', 'noun', 'Quiero un zumo de naranja.', 7, 0, NULL, '[]'::jsonb),
  ('plátano', 'banana', 'noun', 'Los monos comen plátanos.', 7, 0, NULL, '[]'::jsonb),
  ('tomate', 'tomato', 'noun', 'Ensalada de tomate y lechuga.', 7, 0, NULL, '[]'::jsonb),
  ('cebolla', 'onion', 'noun', 'Lloré cortando la cebolla.', 7, 0, NULL, '[]'::jsonb),
  ('patata', 'potato', 'noun', 'Tortilla de patatas, por favor.', 7, 0, NULL, '[]'::jsonb),
  ('arroz', 'rice', 'noun', 'Me gusta el arroz blanco.', 7, 0, NULL, '[]'::jsonb),
  ('sal', 'salt', 'noun', '¿Me pasas la sal?', 7, 0, NULL, '[]'::jsonb),
  ('azúcar', 'sugar', 'noun', 'Un café sin azúcar.', 7, 0, NULL, '[]'::jsonb),
  ('aceite', 'oil', 'noun', 'Aceite de oliva español.', 7, 0, NULL, '[]'::jsonb),
  ('leche', 'milk', 'noun', 'Leche fría o caliente.', 7, 0, NULL, '[]'::jsonb),
  ('café', 'coffee', 'noun', 'Necesito un café fuerte.', 7, 0, NULL, '[]'::jsonb),
  ('té', 'tea', 'noun', 'Me gusta el té verde.', 7, 0, NULL, '[]'::jsonb),
  ('vino', 'wine', 'noun', 'Una botella de vino tinto.', 7, 0, NULL, '[]'::jsonb),
  ('cerveza', 'beer', 'noun', 'Dos cervezas frías, por favor.', 7, 0, NULL, '[]'::jsonb),
  ('desayuno', 'breakfast', 'noun', '¿Qué hay para el desayuno?', 7, 0, NULL, '[]'::jsonb),
  ('almuerzo', 'lunch', 'noun', 'La hora del almuerzo es a la una.', 7, 0, NULL, '[]'::jsonb),
  ('cena', 'dinner', 'noun', '¿Qué vamos a cenar?', 7, 0, NULL, '[]'::jsonb),
  ('viaje', 'trip/journey', 'noun', '¡Buen viaje!', 7, 0, NULL, '[]'::jsonb),
  ('coche', 'car', 'noun', 'Voy en coche al trabajo.', 7, 0, NULL, '[]'::jsonb),
  ('autobús', 'bus', 'noun', 'El autobús llega en cinco minutos.', 7, 0, NULL, '[]'::jsonb),
  ('tren', 'train', 'noun', 'El tren sale de la vía tres.', 7, 0, NULL, '[]'::jsonb),
  ('avión', 'airplane', 'noun', 'Tengo miedo a volar en avión.', 7, 0, NULL, '[]'::jsonb),
  ('bicicleta', 'bicycle', 'noun', 'Me gusta pasear en bicicleta.', 7, 0, NULL, '[]'::jsonb),
  ('calle', 'street', 'noun', 'Vivo en la calle mayor.', 7, 0, NULL, '[]'::jsonb),
  ('camino', 'road/path', 'noun', 'Este camino va al lago.', 7, 0, NULL, '[]'::jsonb),
  ('estación', 'station', 'noun', '¿Dónde está la estación de tren?', 7, 0, NULL, '[]'::jsonb),
  ('aeropuerto', 'airport', 'noun', 'Voy al aeropuerto a recogerla.', 7, 0, NULL, '[]'::jsonb),
  ('billete', 'ticket/bill', 'noun', 'Un billete de ida y vuelta.', 7, 0, NULL, '[]'::jsonb),
  ('hotel', 'hotel', 'noun', 'Nos alojamos en un hotel céntrico.', 7, 0, NULL, '[]'::jsonb),
  ('restaurante', 'restaurant', 'noun', 'Conozco un restaurante muy bueno.', 7, 0, NULL, '[]'::jsonb),
  ('ciudad', 'city', 'noun', 'Madrid es una ciudad hermosa.', 7, 0, NULL, '[]'::jsonb),
  ('pueblo', 'town/village', 'noun', 'Crecí en un pueblo pequeño.', 7, 0, NULL, '[]'::jsonb),
  ('país', 'country', 'noun', 'España es un país de Europa.', 7, 0, NULL, '[]'::jsonb),
  ('mundo', 'world', 'noun', 'Quiero viajar por todo el mundo.', 7, 0, NULL, '[]'::jsonb),
  ('playa', 'beach', 'noun', 'Vamos a la playa este verano.', 7, 0, NULL, '[]'::jsonb),
  ('mar', 'sea', 'noun', 'El mar está muy tranquilo hoy.', 7, 0, NULL, '[]'::jsonb),
  ('montaña', 'mountain', 'noun', 'Nos fuimos de excursión a la montaña.', 7, 0, NULL, '[]'::jsonb),
  ('cabeza', 'head', 'noun', 'Me duele la cabeza.', 8, 0, NULL, '[]'::jsonb),
  ('mano', 'hand', 'noun', 'Dame la mano.', 8, 0, NULL, '[]'::jsonb),
  ('ojo', 'eye', 'noun', 'Ella tiene los ojos azules.', 8, 0, NULL, '[]'::jsonb),
  ('boca', 'mouth', 'noun', 'Cállate la boca.', 8, 0, NULL, '[]'::jsonb),
  ('brazo', 'arm', 'noun', 'Se rompió el brazo.', 8, 0, NULL, '[]'::jsonb),
  ('pierna', 'leg', 'noun', 'Me duelen las piernas de tanto correr.', 8, 0, NULL, '[]'::jsonb),
  ('pie', 'foot', 'noun', 'Tengo frío en los pies.', 8, 0, NULL, '[]'::jsonb),
  ('pelo', 'hair', 'noun', 'Tiene el pelo largo.', 8, 0, NULL, '[]'::jsonb),
  ('cara', 'face', 'noun', 'Lávate la cara.', 8, 0, NULL, '[]'::jsonb),
  ('espalda', 'back', 'noun', 'Me duele mucho la espalda.', 8, 0, NULL, '[]'::jsonb),
  ('estómago', 'stomach', 'noun', 'Tengo dolor de estómago.', 8, 0, NULL, '[]'::jsonb),
  ('corazón', 'heart', 'noun', 'Mi corazón late muy rápido.', 8, 0, NULL, '[]'::jsonb),
  ('sangre', 'blood', 'noun', 'Sale mucha sangre.', 8, 0, NULL, '[]'::jsonb),
  ('hueso', 'bone', 'noun', 'El perro está masticando un hueso.', 8, 0, NULL, '[]'::jsonb),
  ('piel', 'skin', 'noun', 'Tengo la piel seca.', 8, 0, NULL, '[]'::jsonb),
  ('dedo', 'finger/toe', 'noun', 'Me corté el dedo.', 8, 0, NULL, '[]'::jsonb),
  ('enfermo', 'sick', 'adjective', 'Me siento muy enfermo.', 8, 0, NULL, '[]'::jsonb),
  ('dolor', 'pain', 'noun', 'Tengo un dolor terrible.', 8, 0, NULL, '[]'::jsonb),
  ('médico', 'doctor', 'noun', 'Tienes que ir al médico.', 8, 0, NULL, '[]'::jsonb),
  ('hospital', 'hospital', 'noun', 'Mi abuela está en el hospital.', 8, 0, NULL, '[]'::jsonb),
  ('farmacia', 'pharmacy', 'noun', 'Necesito ir a la farmacia.', 8, 0, NULL, '[]'::jsonb),
  ('medicina', 'medicine', 'noun', 'Tómate la medicina.', 8, 0, NULL, '[]'::jsonb),
  ('píldora', 'pill', 'noun', 'Una píldora para dormir.', 8, 0, NULL, '[]'::jsonb),
  ('fiebre', 'fever', 'noun', 'El niño tiene fiebre alta.', 8, 0, NULL, '[]'::jsonb),
  ('tos', 'cough', 'noun', 'Esa tos suena muy mal.', 8, 0, NULL, '[]'::jsonb),
  ('gripe', 'flu', 'noun', 'Hay epidemia de gripe.', 8, 0, NULL, '[]'::jsonb),
  ('resfriado', 'cold', 'noun', 'He cogido un buen resfriado.', 8, 0, NULL, '["illness"]'::jsonb),
  ('accidente', 'accident', 'noun', 'Vi un accidente de coche.', 8, 0, NULL, '[]'::jsonb),
  ('ayuda', 'help', 'noun', '¡Necesito ayuda!', 8, 0, NULL, '[]'::jsonb),
  ('policía', 'police', 'noun', '¡Llama a la policía!', 8, 0, NULL, '[]'::jsonb),
  ('bombero', 'firefighter', 'noun', 'Los bomberos apagaron el fuego.', 8, 0, NULL, '[]'::jsonb),
  ('peligro', 'danger', 'noun', '¡Peligro de muerte!', 8, 0, NULL, '[]'::jsonb),
  ('cuidado', 'care/caution', 'noun', '¡Ten cuidado!', 8, 0, NULL, '[]'::jsonb),
  ('seguro', 'safe/sure', 'adjective', 'Estás seguro aquí.', 8, 0, NULL, '[]'::jsonb),
  ('urgencia', 'emergency', 'noun', 'Es una urgencia médica.', 8, 0, NULL, '[]'::jsonb),
  ('salud', 'health', 'noun', 'El dinero no da la salud.', 8, 0, NULL, '[]'::jsonb),
  ('vida', 'life', 'noun', 'Me salvó la vida.', 8, 0, NULL, '[]'::jsonb),
  ('muerte', 'death', 'noun', 'Vida y muerte.', 8, 0, NULL, '[]'::jsonb),
  ('trabajo', 'work/job', 'noun', 'Busco trabajo.', 10, 0, NULL, '[]'::jsonb),
  ('empresa', 'company', 'noun', 'Trabajo en una gran empresa.', 10, 0, NULL, '[]'::jsonb),
  ('oficina', 'office', 'noun', 'Mi oficina está en el centro.', 10, 0, NULL, '[]'::jsonb),
  ('jefe / jefa', 'boss', 'noun', 'Mi jefe es muy estricto.', 10, 0, NULL, '[]'::jsonb),
  ('dinero', 'money', 'noun', 'No tengo dinero para eso.', 10, 0, NULL, '[]'::jsonb),
  ('banco', 'bank', 'noun', 'Tengo que ir al banco hoy.', 10, 0, NULL, '[]'::jsonb),
  ('precio', 'price', 'noun', '¿Cuál es el precio?', 10, 0, NULL, '[]'::jsonb),
  ('mercado', 'market', 'noun', 'Compramos verduras en el mercado.', 10, 0, NULL, '[]'::jsonb),
  ('tienda', 'store/shop', 'noun', 'Esa tienda cierra a las nueve.', 10, 0, NULL, '[]'::jsonb),
  ('negocio', 'business', 'noun', 'Tienen un negocio familiar.', 10, 0, NULL, '[]'::jsonb),
  ('cliente', 'customer/client', 'noun', 'El cliente siempre tiene la razón.', 10, 0, NULL, '[]'::jsonb),
  ('computadora/ordenador', 'computer', 'noun', 'Uso la computadora todos los días.', 10, 0, NULL, '[]'::jsonb),
  ('pantalla', 'screen', 'noun', 'La pantalla de mi móvil está rota.', 10, 0, NULL, '[]'::jsonb),
  ('teclado', 'keyboard', 'noun', 'Necesito un teclado nuevo.', 10, 0, NULL, '[]'::jsonb),
  ('ratón/mouse', 'mouse', 'noun', 'El ratón no funciona.', 10, 0, NULL, '[]'::jsonb),
  ('internet', 'internet', 'noun', 'Se cayó la conexión a internet.', 10, 0, NULL, '[]'::jsonb),
  ('correo / email', 'mail/email', 'noun', 'Te enviaré un correo mañana.', 10, 0, NULL, '[]'::jsonb),
  ('mensaje', 'message', 'noun', 'Me dejó un mensaje de voz.', 10, 0, NULL, '[]'::jsonb),
  ('red', 'network/net', 'noun', 'La red wifi no funciona.', 10, 0, NULL, '[]'::jsonb),
  ('datos', 'data', 'noun', 'He perdido todos mis datos.', 10, 0, NULL, '[]'::jsonb),
  ('escuela', 'school', 'noun', 'Los niños están en la escuela.', 10, 0, NULL, '[]'::jsonb),
  ('universidad', 'university', 'noun', 'Estudia en la universidad.', 10, 0, NULL, '[]'::jsonb),
  ('clase', 'class', 'noun', 'Tengo clase a las diez.', 10, 0, NULL, '[]'::jsonb),
  ('profesor/profesora', 'teacher', 'noun', 'El profesor es muy aburrido.', 10, 0, NULL, '[]'::jsonb),
  ('estudiante/alumno', 'student', 'noun', 'Soy estudiante universitario.', 10, 0, NULL, '[]'::jsonb),
  ('libro', 'book', 'noun', 'Estoy leyendo un buen libro.', 10, 0, NULL, '[]'::jsonb),
  ('cuaderno', 'notebook', 'noun', 'Escríbelo en tu cuaderno.', 10, 0, NULL, '[]'::jsonb),
  ('lápiz', 'pencil', 'noun', '¿Me prestas un lápiz?', 10, 0, NULL, '[]'::jsonb),
  ('bolígrafo', 'pen', 'noun', 'Necesito un bolígrafo azul.', 10, 0, NULL, '[]'::jsonb),
  ('examen', 'exam/test', 'noun', 'Mañana tengo un examen importante.', 10, 0, NULL, '[]'::jsonb),
  ('pregunta', 'question', 'noun', 'Tengo una pregunta.', 10, 0, NULL, '[]'::jsonb),
  ('respuesta', 'answer', 'noun', 'No sé la respuesta.', 10, 0, NULL, '[]'::jsonb),
  ('ejemplo', 'example', 'noun', 'Por ejemplo, los gatos.', 10, 0, NULL, '[]'::jsonb),
  ('palabra', 'word', 'noun', '¿Qué significa esta palabra?', 10, 0, NULL, '[]'::jsonb),
  ('idioma', 'language', 'noun', 'El español es un idioma hermoso.', 10, 0, NULL, '[]'::jsonb),
  ('historia', 'history/story', 'noun', 'Me gusta la historia antigua.', 10, 0, NULL, '[]'::jsonb),
  ('ciencia', 'science', 'noun', 'La biociencia es el futuro.', 10, 0, NULL, '[]'::jsonb),
  ('arte', 'art', 'noun', 'Un museo de arte moderno.', 10, 0, NULL, '[]'::jsonb),
  ('música', 'music', 'noun', 'Escucho música mientras estudio.', 10, 0, NULL, '[]'::jsonb),
  ('canción', 'song', 'noun', 'Esa canción es mi favorita.', 10, 0, NULL, '[]'::jsonb),
  ('película', 'movie', 'noun', '¿Qué película vamos a ver?', 10, 0, NULL, '[]'::jsonb),
  ('juego', 'game', 'noun', 'Vamos a jugar un juego.', 10, 0, NULL, '[]'::jsonb),
  ('equipo', 'team/equipment', 'noun', 'Nuestro equipo ganó.', 10, 0, NULL, '[]'::jsonb),
  ('con', 'with', 'preposition', 'Lo hice con cuidado.', 9, 0, NULL, '[]'::jsonb),
  ('de', 'of/from', 'preposition', 'La casa de mi madre.', 9, 0, NULL, '[]'::jsonb),
  ('a', 'to/at', 'preposition', 'Voy a dormir.', 9, 0, NULL, '[]'::jsonb),
  ('en', 'in/on', 'preposition', 'Está en la caja.', 9, 0, NULL, '[]'::jsonb),
  ('por', 'for/by', 'preposition', 'Comprado por diez euros.', 9, 0, NULL, '[]'::jsonb),
  ('para', 'for/in order to', 'preposition', 'Es para ti.', 9, 0, NULL, '[]'::jsonb),
  ('sin', 'without', 'preposition', 'Un café sin leche.', 9, 0, NULL, '[]'::jsonb),
  ('sobre', 'about/on/over', 'preposition', 'Hablamos sobre política.', 9, 0, NULL, '[]'::jsonb),
  ('entre', 'between/among', 'preposition', 'Está entre tú y yo.', 9, 0, NULL, '[]'::jsonb),
  ('hasta', 'until/even', 'preposition', 'Trabajo hasta el viernes.', 9, 0, NULL, '[]'::jsonb),
  ('desde', 'from/since', 'preposition', 'Te espero desde ayer.', 9, 0, NULL, '[]'::jsonb),
  ('hacia', 'toward', 'preposition', 'Miró hacia la ventana.', 9, 0, NULL, '[]'::jsonb),
  ('contra', 'against', 'preposition', 'Jugamos contra ellos.', 9, 0, NULL, '[]'::jsonb),
  ('según', 'according to', 'preposition', 'Según las noticias, lloverá.', 9, 0, NULL, '[]'::jsonb),
  ('bajo', 'under', 'preposition', 'El perro está bajo la mesa.', 9, 0, NULL, '[]'::jsonb),
  ('ante', 'before/in the presence of', 'preposition', 'Temblaba ante el juez.', 9, 0, NULL, '[]'::jsonb),
  ('tras', 'after/behind', 'preposition', 'Corrió tras el ladrón.', 9, 0, NULL, '[]'::jsonb),
  ('durante', 'during', 'preposition', 'Llovió durante la noche.', 9, 0, NULL, '[]'::jsonb),
  ('mediante', 'by means of', 'preposition', 'Lo pagó mediante transferencia.', 9, 0, NULL, '[]'::jsonb),
  ('y/e', 'and', 'conjunction', 'Juan y María (Padre e hijo).', 9, 0, NULL, '[]'::jsonb),
  ('o/u', 'or', 'conjunction', '¿Té o café? (Siete u ocho).', 9, 0, NULL, '[]'::jsonb),
  ('pero', 'but', 'conjunction', 'Es tarde, pero me quedo.', 9, 0, NULL, '[]'::jsonb),
  ('sino', 'but rather', 'conjunction', 'No es azul, sino verde.', 9, 0, NULL, '[]'::jsonb),
  ('aunque', 'although/even though', 'conjunction', 'Saldré, aunque llueva.', 9, 0, NULL, '[]'::jsonb),
  ('porque', 'because', 'conjunction', 'Lloro porque estoy triste.', 9, 0, NULL, '[]'::jsonb),
  ('como', 'like/as/since', 'conjunction', 'Canta como un ángel.', 9, 0, NULL, '[]'::jsonb),
  ('si', 'if/whether', 'conjunction', 'Dime si quieres venir.', 9, 0, NULL, '[]'::jsonb),
  ('cuando', 'when', 'conjunction', 'Era joven cuando nos conocimos.', 9, 0, NULL, '[]'::jsonb),
  ('mientras', 'while', 'conjunction', 'Escucha música mientras estudia.', 9, 0, NULL, '[]'::jsonb),
  ('que', 'that/than', 'conjunction/pronoun', 'Quiero que vengas.', 9, 0, NULL, '[]'::jsonb),
  ('donde', 'where', 'conjunction/adverb', 'Vamos donde tú quieras.', 9, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('quien', 'who/whom', 'pronoun', '¿Con quién fuiste?', 9, 0, NULL, '[]'::jsonb),
  ('cual', 'which/who', 'pronoun', 'Esta es la casa en la cual nací.', 9, 0, NULL, '[]'::jsonb),
  ('entonces', 'then', 'adverb/conjunction', 'Entonces, nos vamos.', 9, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('luego', 'later/then', 'adverb', 'Voy al banco y luego a casa.', 9, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('así', 'thus/so/this way', 'adverb', 'No lo hagas así.', 9, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('también', 'also/too', 'adverb', 'Yo también tengo hambre.', 9, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('tampoco', 'neither/not either', 'adverb', 'Yo tampoco sé.', 9, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('ya', 'already/anymore', 'adverb', 'Ya no creo en eso.', 9, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('todavía/aún', 'still/yet', 'adverb', '¿Todavía estás aquí?', 9, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('además', 'besides/in addition', 'adverb', 'Además, es muy caro.', 9, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('incluso', 'even/including', 'adverb/preposition', 'Incluso él lo sabe.', 9, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('tal vez / quizás', 'maybe/perhaps', 'adverb', 'Quizás tengas razón.', 9, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('siempre', 'always', 'adverb', 'Siempre dice la verdad.', 9, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('nunca/jamás', 'never', 'adverb', 'Jamás olvidaré este día.', 9, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('claro', 'of course/clear', 'adjective/adverb', '¡Claro que sí!', 9, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('bueno', 'well.../good', 'adjective/interjection', 'Bueno, me voy.', 9, 0, NULL, '[]'::jsonb),
  ('pues', 'well/since', 'conjunction/interjection', 'Pues no lo sé.', 9, 0, NULL, '[]'::jsonb),
  ('hola', 'hello', 'greeting', '¡Hola, qué tal!', 9, 0, NULL, '[]'::jsonb),
  ('adiós', 'goodbye', 'greeting', '¡Adiós, hasta luego!', 9, 0, NULL, '[]'::jsonb),
  ('gracias', 'thank you', 'greeting', 'Muchas gracias por todo.', 9, 0, NULL, '[]'::jsonb),
  ('por favor', 'please', 'phrase', 'Un café, por favor.', 9, 0, NULL, '[]'::jsonb),
  ('lo siento', 'I''m sorry', 'phrase', 'Lo siento mucho.', 9, 0, NULL, '[]'::jsonb),
  ('perdón', 'excuse me/sorry', 'greeting', 'Perdón, me he equivocado.', 9, 0, NULL, '[]'::jsonb),
  ('de nada', 'you''re welcome', 'phrase', '-¡Gracias! -De nada.', 9, 0, NULL, '[]'::jsonb),
  ('vale', 'okay', 'phrase', 'Vale, nos vemos a las ocho.', 9, 0, NULL, '[]'::jsonb),
  ('feliz', 'happy', 'adjective', 'Ella siempre está feliz.', 4, 0, NULL, '[]'::jsonb),
  ('triste', 'sad', 'adjective', 'Hoy me siento un poco triste.', 4, 0, NULL, '[]'::jsonb),
  ('cansado', 'tired', 'adjective', 'Estoy muy cansado de trabajar.', 4, 0, NULL, '[]'::jsonb),
  ('enfermo', 'sick', 'adjective', 'No voy porque estoy enfermo.', 4, 0, NULL, '[]'::jsonb),
  ('sano', 'healthy', 'adjective', 'Comer fruta te mantiene sano.', 4, 0, NULL, '[]'::jsonb),
  ('fuerte', 'strong', 'adjective', 'Es un hombre muy fuerte.', 4, 0, NULL, '[]'::jsonb),
  ('débil', 'weak', 'adjective', 'Me siento débil.', 4, 0, NULL, '[]'::jsonb),
  ('inteligente', 'intelligent/smart', 'adjective', 'Mi hija es muy inteligente.', 4, 0, NULL, '[]'::jsonb),
  ('tonto', 'silly/dumb', 'adjective', 'No seas tonto.', 4, 0, NULL, '[]'::jsonb),
  ('rápido', 'fast/quick', 'adjective', 'Este coche es muy rápido.', 4, 0, NULL, '[]'::jsonb),
  ('lento', 'slow', 'adjective', 'El autobús va muy lento.', 4, 0, NULL, '[]'::jsonb),
  ('caro', 'expensive', 'adjective', 'Esa casa es demasiado cara.', 4, 0, NULL, '[]'::jsonb),
  ('barato', 'cheap', 'adjective', 'Encontré zapatos muy baratos.', 4, 0, NULL, '[]'::jsonb),
  ('limpio', 'clean', 'adjective', 'Mi habitación está limpia.', 4, 0, NULL, '[]'::jsonb),
  ('sucio', 'dirty', 'adjective', 'Tienes los zapatos sucios.', 4, 0, NULL, '[]'::jsonb),
  ('lleno', 'full', 'adjective', 'El cine estaba lleno.', 4, 0, NULL, '[]'::jsonb),
  ('vacío', 'empty', 'adjective', 'El vaso está vacío.', 4, 0, NULL, '[]'::jsonb),
  ('abierto', 'open', 'adjective', 'La puerta está abierta.', 4, 0, NULL, '[]'::jsonb),
  ('cerrado', 'closed', 'adjective', 'El museo está cerrado los lunes.', 4, 0, NULL, '[]'::jsonb),
  ('fácil', 'easy', 'adjective', 'El examen fue muy fácil.', 4, 0, NULL, '[]'::jsonb),
  ('difícil', 'difficult/hard', 'adjective', 'Aprender ruso es muy difícil.', 4, 0, NULL, '[]'::jsonb),
  ('posible', 'possible', 'adjective', 'Creo que es posible.', 4, 0, NULL, '[]'::jsonb),
  ('imposible', 'impossible', 'adjective', 'Eso es imposible de hacer.', 4, 0, NULL, '[]'::jsonb),
  ('seguro', 'sure/safe', 'adjective', 'Estoy seguro de que vendrá.', 4, 0, NULL, '[]'::jsonb),
  ('peligroso', 'dangerous', 'adjective', 'Conducir rápido es peligroso.', 4, 0, NULL, '[]'::jsonb),
  ('importante', 'important', 'adjective', 'Tenemos una reunión importante.', 4, 0, NULL, '[]'::jsonb),
  ('mismo', 'same', 'adjective', 'Tenemos el mismo coche.', 4, 0, NULL, '[]'::jsonb),
  ('distinto', 'different', 'adjective', 'Somos de países distintos.', 4, 0, NULL, '[]'::jsonb),
  ('único', 'only/unique', 'adjective', 'Es mi único hermano.', 4, 0, NULL, '[]'::jsonb),
  ('solo', 'alone/lonely', 'adjective', 'No me gusta estar solo.', 4, 0, NULL, '[]'::jsonb),
  ('próximo', 'next', 'adjective', 'Nos vemos la próxima semana.', 4, 0, NULL, '[]'::jsonb),
  ('último', 'last/final', 'adjective', 'Es la última vez que te lo digo.', 4, 0, NULL, '[]'::jsonb),
  ('anterior', 'previous', 'adjective', 'En la página anterior.', 4, 0, NULL, '[]'::jsonb),
  ('siguiente', 'following/next', 'adjective', 'Lea el siguiente párrafo.', 4, 0, NULL, '[]'::jsonb),
  ('cierto', 'true/certain', 'adjective', 'Eso no es cierto.', 4, 0, NULL, '[]'::jsonb),
  ('falso', 'false/fake', 'adjective', 'Las noticias eran falsas.', 4, 0, NULL, '[]'::jsonb),
  ('claro', 'clear/light', 'adjective', 'El agua está muy clara.', 4, 0, NULL, '[]'::jsonb),
  ('oscuro', 'dark', 'adjective', 'El cuarto está oscuro.', 4, 0, NULL, '[]'::jsonb),
  ('pesado', 'heavy', 'adjective', 'Esta caja es muy pesada.', 4, 0, NULL, '[]'::jsonb),
  ('ligero', 'light', 'adjective', 'Necesito equipaje ligero.', 4, 0, NULL, '["weight"]'::jsonb),
  ('duro', 'hard', 'adjective', 'Este pan está muy duro.', 4, 0, NULL, '[]'::jsonb),
  ('suave', 'soft/smooth', 'adjective', 'Tiene la piel muy suave.', 4, 0, NULL, '[]'::jsonb),
  ('frío', 'cold', 'adjective', 'El invierno es frío.', 4, 0, NULL, '[]'::jsonb),
  ('caliente', 'hot', 'adjective', 'Ten cuidado, el plato está caliente.', 4, 0, NULL, '[]'::jsonb),
  ('seco', 'dry', 'adjective', 'Necesito un paño seco.', 4, 0, NULL, '[]'::jsonb),
  ('mojado', 'wet', 'adjective', 'Estoy mojado por la lluvia.', 4, 0, NULL, '[]'::jsonb),
  ('rico', 'rich/delicious', 'adjective', 'La comida está rica.', 4, 0, NULL, '[]'::jsonb),
  ('pobre', 'poor', 'adjective', 'Viven en un país pobre.', 4, 0, NULL, '[]'::jsonb),
  ('joven', 'young', 'adjective', 'Ella es muy joven aún.', 4, 0, NULL, '[]'::jsonb),
  ('viejo', 'old', 'adjective', 'Mi coche es viejo, pero funciona.', 4, 0, NULL, '[]'::jsonb),
  ('nuevo', 'new', 'adjective', 'Compré un libro nuevo.', 4, 0, NULL, '[]'::jsonb),
  ('alto', 'tall/high', 'adjective', 'El edificio es muy alto.', 4, 0, NULL, '[]'::jsonb),
  ('bajo', 'short/low', 'adjective', 'El techo de la casa es bajo.', 4, 0, NULL, '[]'::jsonb),
  ('largo', 'long', 'adjective', 'Tiene el pelo largo.', 4, 0, NULL, '[]'::jsonb),
  ('corto', 'short', 'adjective', 'El camino más corto es por aquí.', 4, 0, NULL, '["length"]'::jsonb),
  ('ancho', 'wide/broad', 'adjective', 'Es un río muy ancho.', 4, 0, NULL, '[]'::jsonb),
  ('estrecho', 'narrow', 'adjective', 'La calle es muy estrecha.', 4, 0, NULL, '[]'::jsonb),
  ('bueno', 'good', 'adjective', 'Este es un buen amigo.', 4, 0, NULL, '[]'::jsonb),
  ('malo', 'bad', 'adjective', 'Hace muy mal tiempo.', 4, 0, NULL, '[]'::jsonb),
  ('mejor', 'better/best', 'adjective', 'Ella es la mejor estudiante.', 4, 0, NULL, '[]'::jsonb),
  ('peor', 'worse/worst', 'adjective', 'Fue el peor viaje de mi vida.', 4, 0, NULL, '[]'::jsonb),
  ('mayor', 'older/larger', 'adjective', 'Mi hermano mayor vive lejos.', 4, 0, NULL, '[]'::jsonb),
  ('menor', 'younger/smaller', 'adjective', 'Mi hermana menor va a la escuela.', 4, 0, NULL, '[]'::jsonb),
  ('hoy', 'today', 'adverb', 'Hoy hace un día precioso.', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('ayer', 'yesterday', 'adverb', 'Ayer trabajé mucho.', 5, 0, '''{"yo":"ayo","tu":"ayes","el":"aye","nosotros":"ayemos","vosotros":"ayéis","ellos":"ayen","gerundio":"ayiendo"}''::jsonb'::jsonb, '[]'::jsonb),
  ('mañana', 'tomorrow/morning', 'noun', 'Mañana nos vemos.', 5, 0, NULL, '[]'::jsonb),
  ('ahora', 'now', 'adverb', 'Tienes que salir ahora mismo.', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('antes', 'before', 'adverb', 'Tuviste que decírmelo antes.', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('después', 'after/later', 'adverb', 'Te llamo después.', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('siempre', 'always', 'adverb', 'Siempre me acuesto tarde.', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('nunca', 'never', 'adverb', 'Nunca he estado allí.', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('pronto', 'soon', 'adverb', 'Espero verte pronto.', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('tarde', 'late/afternoon', 'adverb', 'Llegaste muy tarde al tren.', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('temprano', 'early', 'adverb', 'Me levanto muy temprano.', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('ya', 'already/now', 'adverb', 'Ya he terminado el trabajo.', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('todavía', 'still', 'adverb', '¿Todavía estás comiendo?', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('aún', 'still/yet', 'adverb', 'Aún no, espérate.', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('entonces', 'then', 'adverb', 'Entonces, ¿qué hacemos?', 5, 0, '''null''::jsonb'::jsonb, '[]'::jsonb),
  ('mientras', 'while', 'conjunction', 'Escucho música mientras estudio.', 5, 0, NULL, '[]'::jsonb),
  ('durante', 'during', 'preposition', 'Me dormí durante la película.', 5, 0, NULL, '[]'::jsonb),
  ('vez', 'time/instance', 'noun', 'Es la primera vez que vengo.', 5, 0, NULL, '[]'::jsonb),
  ('veces', 'times', 'noun', 'Fui allí muchas veces.', 5, 0, NULL, '[]'::jsonb),
  ('hora', 'hour/time', 'noun', '¿Qué hora es?', 5, 0, NULL, '[]'::jsonb),
  ('minuto', 'minute', 'noun', 'Faltan cinco minutos.', 5, 0, NULL, '[]'::jsonb),
  ('segundo', 'second', 'noun', 'Espera un segundo.', 5, 0, NULL, '[]'::jsonb),
  ('día', 'day', 'noun', 'Buenos días.', 5, 0, NULL, '[]'::jsonb),
  ('semana', 'week', 'noun', 'Nos vamos de vacaciones la próxima semana.', 5, 0, NULL, '[]'::jsonb),
  ('mes', 'month', 'noun', 'Enero es el primer mes del año.', 5, 0, NULL, '[]'::jsonb),
  ('año', 'year', 'noun', 'Feliz Año Nuevo.', 5, 0, NULL, '[]'::jsonb),
  ('siglo', 'century', 'noun', 'Vivimos en el siglo veintiuno.', 5, 0, NULL, '[]'::jsonb),
  ('estación', 'season/station', 'noun', 'El verano es mi estación favorita.', 5, 0, NULL, '[]'::jsonb),
  ('primavera', 'spring', 'noun', 'Las flores nacen en primavera.', 5, 0, NULL, '[]'::jsonb),
  ('verano', 'summer', 'noun', 'Hace calor en verano.', 5, 0, NULL, '[]'::jsonb),
  ('otoño', 'autumn/fall', 'noun', 'Las hojas caen en otoño.', 5, 0, NULL, '[]'::jsonb),
  ('invierno', 'winter', 'noun', 'En invierno hace mucho frío.', 5, 0, NULL, '[]'::jsonb),
  ('lunes', 'Monday', 'noun', 'Odio los lunes.', 5, 0, NULL, '[]'::jsonb),
  ('martes', 'Tuesday', 'noun', 'El martes tengo clase de tenis.', 5, 0, NULL, '[]'::jsonb),
  ('miércoles', 'Wednesday', 'noun', 'El miércoles es mitad de semana.', 5, 0, NULL, '[]'::jsonb),
  ('jueves', 'Thursday', 'noun', 'Este jueves voy al cine.', 5, 0, NULL, '[]'::jsonb),
  ('viernes', 'Friday', 'noun', 'Por fin es viernes.', 5, 0, NULL, '[]'::jsonb),
  ('sábado', 'Saturday', 'noun', 'El sábado hay una fiesta.', 5, 0, NULL, '[]'::jsonb),
  ('domingo', 'Sunday', 'noun', 'Los domingos descanso.', 5, 0, NULL, '[]'::jsonb),
  ('enero', 'January', 'noun', 'Nací en enero.', 5, 0, NULL, '[]'::jsonb),
  ('febrero', 'February', 'noun', 'Febrero es el mes más corto.', 5, 0, NULL, '[]'::jsonb),
  ('marzo', 'March', 'noun', 'En marzo empieza la primavera aquí.', 5, 0, NULL, '[]'::jsonb),
  ('abril', 'April', 'noun', 'Aguas mil en abril.', 5, 0, NULL, '[]'::jsonb),
  ('mayo', 'May', 'noun', 'Mi madre cumple años en mayo.', 5, 0, NULL, '[]'::jsonb),
  ('junio', 'June', 'noun', 'En junio terminan las clases.', 5, 0, NULL, '[]'::jsonb),
  ('julio', 'July', 'noun', 'Me voy de vacaciones en julio.', 5, 0, NULL, '[]'::jsonb),
  ('agosto', 'August', 'noun', 'Hace demasiado calor en agosto.', 5, 0, NULL, '[]'::jsonb),
  ('septiembre', 'September', 'noun', 'En septiembre vuelvo a estudiar.', 5, 0, NULL, '[]'::jsonb),
  ('octubre', 'October', 'noun', 'Halloween es en octubre.', 5, 0, NULL, '[]'::jsonb),
  ('noviembre', 'November', 'noun', 'Hace frío en noviembre.', 5, 0, NULL, '[]'::jsonb),
  ('diciembre', 'December', 'noun', 'Navidad es en diciembre.', 5, 0, NULL, '[]'::jsonb),
  ('uno', 'one', 'number', 'Quiero un café, por favor.', 5, 0, NULL, '[]'::jsonb),
  ('dos', 'two', 'number', 'Tengo dos perros.', 5, 0, NULL, '[]'::jsonb),
  ('tres', 'three', 'number', 'Somos tres hermanos.', 5, 0, NULL, '[]'::jsonb),
  ('cuatro', 'four', 'number', 'El coche tiene cuatro puertas.', 5, 0, NULL, '[]'::jsonb),
  ('cinco', 'five', 'number', 'Faltan cinco kilómetros.', 5, 0, NULL, '[]'::jsonb),
  ('seis', 'six', 'number', 'Me levanto a las seis de la mañana.', 5, 0, NULL, '[]'::jsonb),
  ('siete', 'seven', 'number', 'Trabajo los siete días de la semana.', 5, 0, NULL, '[]'::jsonb),
  ('ocho', 'eight', 'number', 'Duermo ocho horas diarias.', 5, 0, NULL, '[]'::jsonb),
  ('nueve', 'nine', 'number', 'Mi número de la suerte es el nueve.', 5, 0, NULL, '[]'::jsonb),
  ('diez', 'ten', 'number', 'Costó diez euros.', 5, 0, NULL, '[]'::jsonb),
  ('veinte', 'twenty', 'number', 'Cumplo veinte años.', 5, 0, NULL, '[]'::jsonb),
  ('treinta', 'thirty', 'number', 'El autobús llegó treinta minutos tarde.', 5, 0, NULL, '[]'::jsonb),
  ('cuarenta', 'forty', 'number', 'Mi padre tiene cuarenta años.', 5, 0, NULL, '[]'::jsonb),
  ('cincuenta', 'fifty', 'number', 'Cincuenta sombras de Grey.', 5, 0, NULL, '[]'::jsonb),
  ('cien', 'hundred/one hundred', 'number', 'Pagué cien dólares.', 5, 0, NULL, '[]'::jsonb),
  ('mil', 'thousand', 'number', 'Aquel vestido vale mil pesos.', 5, 0, NULL, '[]'::jsonb),
  ('millón', 'million', 'number', 'Un millón de gracias.', 5, 0, NULL, '[]'::jsonb),
  ('primero', 'first', 'adjective', 'Esta es mi primera vez aquí.', 5, 0, NULL, '[]'::jsonb),
  ('segundo', 'second', 'adjective', 'Piso segundo, puerta B.', 5, 0, NULL, '[]'::jsonb),
  ('tercero', 'third', 'adjective', 'Quedó el tercero de la carrera.', 5, 0, NULL, '[]'::jsonb),
  ('venir', 'to come', 'verb', 'Vengo de muy lejos.', 3, 0, '''{"yo":"vengo","tu":"vienes","el":"viene","nosotros":"venimos","vosotros":"venís","ellos":"vienen","gerundio":"viniendo"}''::jsonb'::jsonb, '["irregular e->ie"]'::jsonb),
  ('querer', 'to want/love', 'verb', 'Te quiero con toda mi alma.', 3, 0, '''{"yo":"quiero","tu":"quieres","el":"quiere","nosotros":"queremos","vosotros":"queréis","ellos":"quieren","gerundio":"queriendo"}''::jsonb'::jsonb, '["irregular e->ie"]'::jsonb),
  ('hacer', 'to do/make', 'verb', '¿Qué vas a hacer hoy?', 3, 0, '''{"yo":"hago","tu":"haces","el":"hace","nosotros":"hacemos","vosotros":"hacéis","ellos":"hacen","gerundio":"haciendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('decir', 'to say/tell', 'verb', 'Siempre me dice la verdad.', 3, 0, '''{"yo":"digo","tu":"dices","el":"dice","nosotros":"decimos","vosotros":"decís","ellos":"dicen","gerundio":"diciendo"}''::jsonb'::jsonb, '["irregular e->i"]'::jsonb),
  ('poder', 'to be able to/can', 'verb', '¿Puedo pasar?', 3, 0, '''{"yo":"puedo","tu":"puedes","el":"puede","nosotros":"podemos","vosotros":"podéis","ellos":"pueden","gerundio":"pudiendo"}''::jsonb'::jsonb, '["irregular o->ue"]'::jsonb),
  ('poner', 'to put/place', 'verb', 'Pon las llaves aquí.', 3, 0, '''{"yo":"pongo","tu":"pones","el":"pone","nosotros":"ponemos","vosotros":"ponéis","ellos":"ponen","gerundio":"poniendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('salir', 'to leave/go out', 'verb', 'Salgo del trabajo a las seis.', 3, 0, '''{"yo":"salgo","tu":"sales","el":"sale","nosotros":"salimos","vosotros":"salís","ellos":"salen","gerundio":"saliendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('dar', 'to give', 'verb', 'Dame tu mano.', 3, 0, '''{"yo":"doy","tu":"das","el":"da","nosotros":"damos","vosotros":"dais","ellos":"dan","gerundio":"dando"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('saber', 'to know', 'verb', 'Yo no sé nada.', 3, 0, '''{"yo":"sé","tu":"sabes","el":"sabe","nosotros":"sabemos","vosotros":"sabéis","ellos":"saben","gerundio":"sabiendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('conocer', 'to know a person/place', 'verb', 'Conozco a tu hermana.', 3, 0, '''{"yo":"conozco","tu":"conoces","el":"conoce","nosotros":"conocemos","vosotros":"conocéis","ellos":"conocen","gerundio":"conociendo"}''::jsonb'::jsonb, '["irregular"]'::jsonb),
  ('pensar', 'to think', 'verb', 'Pienso que es mejor así.', 3, 0, '''{"yo":"pienso","tu":"piensas","el":"piensa","nosotros":"pensamos","vosotros":"pensáis","ellos":"piensan","gerundio":"pensando"}''::jsonb'::jsonb, '["irregular e->ie"]'::jsonb),
  ('empezar', 'to begin/start', 'verb', 'La clase empieza ahora.', 3, 0, '''{"yo":"empiezo","tu":"empiezas","el":"empieza","nosotros":"empezamos","vosotros":"empezáis","ellos":"empiezan","gerundio":"empezando"}''::jsonb'::jsonb, '["irregular e->ie"]'::jsonb),
  ('entender', 'to understand', 'verb', 'Sigo sin entender.', 3, 0, '''{"yo":"entiendo","tu":"entiendes","el":"entiende","nosotros":"entendemos","vosotros":"entendéis","ellos":"entienden","gerundio":"entendiendo"}''::jsonb'::jsonb, '["irregular e->ie"]'::jsonb),
  ('sentir', 'to feel/regret', 'verb', 'Lo siento muchísimo.', 3, 0, '''{"yo":"siento","tu":"sientes","el":"siente","nosotros":"sentimos","vosotros":"sentís","ellos":"sienten","gerundio":"sintiendo"}''::jsonb'::jsonb, '["irregular e->ie"]'::jsonb),
  ('dormir', 'to sleep', 'verb', 'Intento dormir ocho horas.', 3, 0, '''{"yo":"duermo","tu":"duermes","el":"duerme","nosotros":"dormimos","vosotros":"dormís","ellos":"duermen","gerundio":"durmiendo"}''::jsonb'::jsonb, '["irregular o->ue"]'::jsonb),
  ('pedir', 'to ask for/request', 'verb', 'Voy a pedir dinero prestado.', 3, 0, '''{"yo":"pido","tu":"pides","el":"pide","nosotros":"pedimos","vosotros":"pedís","ellos":"piden","gerundio":"pidiendo"}''::jsonb'::jsonb, '["irregular e->i"]'::jsonb),
  ('seguir', 'to follow/continue', 'verb', 'Sigue todo recto.', 3, 0, '''{"yo":"sigo","tu":"sigues","el":"sigue","nosotros":"seguimos","vosotros":"seguís","ellos":"siguen","gerundio":"siguiendo"}''::jsonb'::jsonb, '["irregular e->i"]'::jsonb),
  ('volver', 'to return/go back', 'verb', 'Vuelvo en un rato.', 3, 0, '''{"yo":"vuelvo","tu":"vuelves","el":"vuelve","nosotros":"volvemos","vosotros":"volvéis","ellos":"vuelven","gerundio":"volviendo"}''::jsonb'::jsonb, '["irregular o->ue"]'::jsonb),
  ('encontrar', 'to find', 'verb', 'No encuentro mi cartera.', 3, 0, '''{"yo":"encuentro","tu":"encuentras","el":"encuentra","nosotros":"encontramos","vosotros":"encontráis","ellos":"encuentran","gerundio":"encontrando"}''::jsonb'::jsonb, '["irregular o->ue"]'::jsonb),
  ('jugar', 'to play', 'verb', 'Vamos a jugar un rato.', 3, 0, '''{"yo":"juego","tu":"juegas","el":"juega","nosotros":"jugamos","vosotros":"jugáis","ellos":"juegan","gerundio":"jugando"}''::jsonb'::jsonb, '["irregular u->ue"]'::jsonb),
  ('mostrar', 'to show', 'verb', 'Muéstrame el camino.', 3, 0, '''{"yo":"muestro","tu":"muestras","el":"muestra","nosotros":"mostramos","vosotros":"mostráis","ellos":"muestran","gerundio":"mostrando"}''::jsonb'::jsonb, '["irregular o->ue"]'::jsonb),
  ('viaje', 'trip/journey', 'noun', '¡Feliz viaje!', 10, 0, NULL, '[]'::jsonb),
  ('coche / carro/ auto', 'car', 'noun', 'Vamos en coche.', 10, 0, NULL, '[]'::jsonb),
  ('tren', 'train', 'noun', 'El tren de alta velocidad.', 10, 0, NULL, '[]'::jsonb),
  ('avión', 'airplane', 'noun', 'Nunca he viajado en avión.', 10, 0, NULL, '[]'::jsonb),
  ('aeropuerto', 'airport', 'noun', 'Llegamos al aeropuerto temprano.', 10, 0, NULL, '[]'::jsonb),
  ('boleto / billete', 'ticket', 'noun', 'Un billete de ida, por favor.', 10, 0, NULL, '[]'::jsonb),
  ('equipaje', 'luggage', 'noun', 'Hemos perdido mi equipaje.', 10, 0, NULL, '[]'::jsonb),
  ('hotel', 'hotel', 'noun', 'Un hotel de cinco estrellas.', 10, 0, NULL, '[]'::jsonb),
  ('habitación', 'room', 'noun', 'Una habitación doble.', 10, 0, NULL, '[]'::jsonb),
  ('reserva', 'reservation', 'noun', 'Tengo una reserva a mi nombre.', 10, 0, NULL, '[]'::jsonb),
  ('mapa', 'map', 'noun', 'Mira el mapa en tu celular.', 10, 0, NULL, '[]'::jsonb),
  ('calle', 'street', 'noun', 'Cruza la calle con cuidado.', 10, 0, NULL, '[]'::jsonb),
  ('ciudad', 'city', 'noun', 'Es una ciudad muy ruidosa.', 10, 0, NULL, '[]'::jsonb),
  ('pueblo', 'town/village', 'noun', 'Viven en un pueblo pequeño.', 10, 0, NULL, '[]'::jsonb),
  ('campo', 'country/field', 'noun', 'Fin de semana en el campo.', 10, 0, NULL, '[]'::jsonb),
  ('lugar', 'place', 'noun', 'Este es mi lugar favorito.', 10, 0, NULL, '[]'::jsonb),
  ('país', 'country', 'noun', 'Visité tres países en Europa.', 10, 0, NULL, '[]'::jsonb),
  ('mundo', 'world', 'noun', 'Quiero dar la vuelta al mundo.', 10, 0, NULL, '[]'::jsonb),
  ('sol', 'sun', 'noun', 'Hoy hace mucho sol.', 10, 0, NULL, '[]'::jsonb),
  ('luna', 'moon', 'noun', 'Hay luna llena esta noche.', 10, 0, NULL, '[]'::jsonb),
  ('estrella', 'star', 'noun', 'Cuenta las estrellas.', 10, 0, NULL, '[]'::jsonb),
  ('cielo', 'sky', 'noun', 'El cielo está muy azul.', 10, 0, NULL, '[]'::jsonb),
  ('lluvia', 'rain', 'noun', 'La lluvia cae suavemente.', 10, 0, NULL, '[]'::jsonb),
  ('nieve', 'snow', 'noun', 'Me encanta jugar en la nieve.', 10, 0, NULL, '[]'::jsonb),
  ('viento', 'wind', 'noun', 'Hace un viento helado.', 10, 0, NULL, '[]'::jsonb),
  ('árbol', 'tree', 'noun', 'El pájaro está en el árbol.', 10, 0, NULL, '[]'::jsonb),
  ('flor', 'flower', 'noun', 'Le compré unas flores hermosas.', 10, 0, NULL, '[]'::jsonb),
  ('río', 'river', 'noun', 'Nos bañamos en el río.', 10, 0, NULL, '[]'::jsonb),
  ('lago', 'lake', 'noun', 'Tienen una casa en el lago.', 10, 0, NULL, '[]'::jsonb),
  ('mar', 'sea', 'noun', 'Nadar en el mar.', 10, 0, NULL, '[]'::jsonb),
  ('playa', 'beach', 'noun', 'Día soleado en la playa.', 10, 0, NULL, '[]'::jsonb),
  ('montaña', 'mountain', 'noun', 'Subimos a la montaña.', 10, 0, NULL, '[]'::jsonb),
  ('fuego', 'fire', 'noun', '¡Cuidado con el fuego!', 10, 0, NULL, '[]'::jsonb),
  ('tierra', 'earth/land/dirt', 'noun', 'Tenemos los pies en la tierra.', 10, 0, NULL, '[]'::jsonb),
  ('animal', 'animal', 'noun', 'Me gustan mucho los animales.', 10, 0, NULL, '[]'::jsonb),
  ('perro', 'dog', 'noun', 'Saca a pasear al perro.', 10, 0, NULL, '[]'::jsonb),
  ('gato', 'cat', 'noun', 'El gato duerme en el sofá.', 10, 0, NULL, '[]'::jsonb),
  ('pájaro', 'bird', 'noun', 'El pájaro canta por la mañana.', 10, 0, NULL, '[]'::jsonb),
  ('pez', 'fish', 'noun', 'En el acuario hay muchos peces.', 10, 0, NULL, '["alive"]'::jsonb),
  ('color', 'color', 'noun', '¿Cuál es tu color favorito?', 10, 0, NULL, '[]'::jsonb),
  ('rojo', 'red', 'adjective', 'Tiene un vestido rojo.', 10, 0, NULL, '[]'::jsonb),
  ('azul', 'blue', 'adjective', 'El cielo está más azul hoy.', 10, 0, NULL, '[]'::jsonb),
  ('verde', 'green', 'adjective', 'La hierba es verde.', 10, 0, NULL, '[]'::jsonb),
  ('amarillo', 'yellow', 'adjective', 'Un taxi amarillo brillante.', 10, 0, NULL, '[]'::jsonb),
  ('negro', 'black', 'adjective', 'Un gato negro cruzó la calle.', 10, 0, NULL, '[]'::jsonb),
  ('blanco', 'white', 'adjective', 'Nubes blancas en el cielo.', 10, 0, NULL, '[]'::jsonb),
  ('gris', 'gray', 'adjective', 'Hoy es un día gris y triste.', 10, 0, NULL, '[]'::jsonb),
  ('marrón', 'brown', 'adjective', 'Sus ojos son muy marrones.', 10, 0, NULL, '[]'::jsonb),
  ('naranja', 'orange', 'adjective', 'Una camisa naranja neón.', 10, 0, NULL, '[]'::jsonb),
  ('rosa', 'pink', 'adjective', 'Su cuarto está pintado de rosa.', 10, 0, NULL, '[]'::jsonb),
  ('blanco/claro', 'clear/light', 'adjective', 'Un azul muy claro.', 10, 0, NULL, '["color"]'::jsonb),
  ('oscuro', 'dark', 'adjective', 'Me gusta el azul oscuro.', 10, 0, NULL, '["color"]'::jsonb),
  ('brillante', 'shiny/bright', 'adjective', 'Una estrella muy brillante.', 10, 0, NULL, '[]'::jsonb),
  ('opaco', 'opaque/dull', 'adjective', 'Un cristal opaco.', 10, 0, NULL, '[]'::jsonb),
  ('ruidoso', 'noisy/loud', 'adjective', 'Es un bar demasiado ruidoso.', 10, 0, NULL, '[]'::jsonb),
  ('silencioso', 'quiet/silent', 'adjective', 'La biblioteca es muy silenciosa.', 10, 0, NULL, '[]'::jsonb),
  ('suave', 'soft', 'adjective', 'Una manta muy suave.', 10, 0, NULL, '[]'::jsonb),
  ('áspero', 'rough', 'adjective', 'Tiene las manos ásperas.', 10, 0, NULL, '[]'::jsonb),
  ('dulce', 'sweet', 'adjective', 'Este postre es muy dulce.', 10, 0, NULL, '[]'::jsonb),
  ('salado', 'salty', 'adjective', 'La sopa está muy salada.', 10, 0, NULL, '[]'::jsonb),
  ('amargo', 'bitter', 'adjective', 'El café negro es muy amargo.', 10, 0, NULL, '[]'::jsonb),
  ('picante', 'spicy', 'adjective', 'La salsa mexicana es picante.', 10, 0, NULL, '[]'::jsonb),
  ('ácido', 'sour', 'adjective', 'El limón es muy ácido.', 10, 0, NULL, '[]'::jsonb),
  ('sistema', 'system', 'noun', 'El sistema está roto.', 10, 0, NULL, '[]'::jsonb),
  ('problema', 'problem', 'noun', 'No hay ningún problema.', 10, 0, NULL, '[]'::jsonb),
  ('programa', 'program', 'noun', 'Cuál es tu programa favorito.', 10, 0, NULL, '[]'::jsonb),
  ('punto', 'point', 'noun', 'Llegaste al punto principal.', 10, 0, NULL, '[]'::jsonb),
  ('estado', 'state/condition', 'noun', 'El estado de la economía.', 10, 0, NULL, '[]'::jsonb),
  ('forma', 'shape/form/way', 'noun', 'Una forma diferente de ver las cosas.', 10, 0, NULL, '[]'::jsonb),
  ('parte', 'part/portion', 'noun', 'Te toca esta parte.', 10, 0, NULL, '[]'::jsonb),
  ('lugar', 'place', 'noun', 'Pon cada cosa en su lugar.', 10, 0, NULL, '[]'::jsonb),
  ('caso', 'case', 'noun', 'En cualquier caso, no importa.', 10, 0, NULL, '[]'::jsonb),
  ('vez', 'time/instance', 'noun', 'Había una vez...', 10, 0, NULL, '[]'::jsonb),
  ('idea', 'idea', 'noun', '¡Qué buena idea!', 10, 0, NULL, '[]'::jsonb),
  ('verdad', 'truth', 'noun', 'Dime la pura verdad.', 10, 0, NULL, '[]'::jsonb),
  ('realidad', 'reality', 'noun', 'En realidad no sé.', 10, 0, NULL, '[]'::jsonb),
  ('cambio', 'change', 'noun', 'El mundo necesita un cambio.', 10, 0, NULL, '[]'::jsonb),
  ('razón', 'reason/right', 'noun', 'Tienes toda la razón del mundo.', 10, 0, NULL, '[]'::jsonb),
  ('cuenta', 'account/bill', 'noun', 'La cuenta, por favor.', 10, 0, NULL, '[]'::jsonb),
  ('modo', 'way/manner', 'noun', 'De este modo es más fácil.', 10, 0, NULL, '[]'::jsonb),
  ('nivel', 'level', 'noun', 'Estás a un nivel avanzado.', 10, 0, NULL, '[]'::jsonb),
  ('Fín', 'end', 'phrase', 'El fín justifica los medios.', 10, 0, NULL, '[]'::jsonb),
  ('claro', 'clear', 'adjective', 'Está muy claro.', 10, 0, NULL, '[]'::jsonb),
  ('directo', 'direct', 'adjective', 'Un vuelo directo.', 10, 0, NULL, '[]'::jsonb),
  ('seguro', 'sure', 'adjective', 'Estoy muy seguro.', 10, 0, NULL, '[]'::jsonb),
  ('posible', 'possible', 'adjective', 'Sí, es posible.', 10, 0, NULL, '[]'::jsonb),
  ('diferente', 'different', 'adjective', 'Es algo diferente.', 10, 0, NULL, '[]'::jsonb),
  ('fuerte', 'strong', 'adjective', 'Un café fuerte.', 10, 0, NULL, '[]'::jsonb);

-- Explicitly drop the previous foreign key and recreate it to ensure it references the correct table
ALTER TABLE IF EXISTS public.user_progress
DROP CONSTRAINT IF EXISTS user_progress_word_id_fkey,
ADD CONSTRAINT user_progress_word_id_fkey 
FOREIGN KEY (word_id) REFERENCES public.words(id) ON DELETE CASCADE;
