-- Drop the existing table and recreate it to ensure a clean slate
DROP TABLE IF EXISTS public.words;

CREATE TABLE public.words (
    id SERIAL PRIMARY KEY,
    en TEXT NOT NULL,
    es TEXT NOT NULL,
    type TEXT,
    ex TEXT,
    p INTEGER DEFAULT 1,
    lvl INTEGER DEFAULT 0
);

-- Turn on Row Level Security
ALTER TABLE public.words ENABLE ROW LEVEL SECURITY;

-- Allow read access to all authenticated users
CREATE POLICY "Enable read access for all authenticated users"
ON public.words FOR SELECT
TO authenticated USING (true);

-- Explicitly drop the previous foreign key and recreate it to ensure it references the correct table
ALTER TABLE IF EXISTS public.user_progress
DROP CONSTRAINT IF EXISTS user_progress_word_id_fkey,
ADD CONSTRAINT user_progress_word_id_fkey 
FOREIGN KEY (word_id) REFERENCES public.words(id) ON DELETE CASCADE;

INSERT INTO public.words (en, es, type, ex, p, lvl) VALUES
  ('el/la', 'the', 'article', 'El perro y la gata juegan.', 1, 0),
  ('un/una', 'a/an', 'article', 'Quiero una manzana y un plátano.', 1, 0),
  ('de', 'of/from', 'preposition', 'Soy de Madrid.', 1, 0),
  ('que', 'that/which', 'conjunction', 'El libro que leí es bueno.', 1, 0),
  ('y', 'and', 'conjunction', 'Tú y yo somos amigos.', 1, 0),
  ('en', 'in/on/at', 'preposition', 'Estamos en la casa.', 1, 0),
  ('a', 'to/at', 'preposition', 'Voy a la escuela.', 1, 0),
  ('ser', 'to be (regular irr.)', 'verb', 'Quiero ser doctor.', 1, 0),
  ('él/ella', 'he/she', 'pronoun', 'Él es alto y ella es baja.', 1, 0),
  ('no', 'no/not', 'adverb', 'No quiero salir hoy.', 1, 0),
  ('tener', 'to have (irregular)', 'verb', 'Tengo un coche nuevo.', 1, 0),
  ('un/uno', 'one', 'number', 'Solo tengo un hermano.', 1, 0),
  ('por', 'for/by', 'preposition', 'Gracias por tu ayuda.', 1, 0),
  ('con', 'with', 'preposition', 'Voy al cine con mis amigos.', 1, 0),
  ('su', 'his/her/their', 'determiner', 'Su casa es muy grande.', 1, 0),
  ('para', 'for/in order to', 'preposition', 'Este regalo es para ti.', 1, 0),
  ('como', 'like/as', 'conjunction', 'Eres fuerte como un toro.', 1, 0),
  ('estar', 'to be (irregular)', 'verb', 'Estoy muy cansado.', 1, 0),
  ('me', 'me/myself', 'pronoun', 'Me gusta mucho la música.', 1, 0),
  ('más', 'more', 'adverb', 'Quiero más agua, por favor.', 1, 0),
  ('lo', 'it/him', 'pronoun', 'Lo vi ayer en el supermercado.', 1, 0),
  ('o', 'or', 'conjunction', '¿Quieres té o café?', 1, 0),
  ('pero', 'but', 'conjunction', 'Es caro, pero es bueno.', 1, 0),
  ('hacer', 'to do/to make (irregular)', 'verb', 'Tengo que hacer mi tarea.', 1, 0),
  ('le', 'to him/her/it', 'pronoun', 'Le di el libro a Juan.', 1, 0),
  ('poder', 'to be able to/can (irregular o->ue)', 'verb', '¿Puedo ir al baño?', 1, 0),
  ('decir', 'to say/tell (irregular e->i)', 'verb', 'Tienes que decir la verdad.', 1, 0),
  ('este/esta', 'this', 'determiner', 'Este coche es muy rápido.', 1, 0),
  ('ir', 'to go (irregular)', 'verb', 'Voy a ir a la playa mañana.', 1, 0),
  ('otro/otra', 'another/other', 'adjective', 'Quiero otro trozo de pastel.', 1, 0),
  ('ese/esa', 'that', 'determiner', 'Ese perro es muy amigable.', 1, 0),
  ('la', 'the (fem) / her/it', 'pronoun', 'La vi en el parque.', 1, 0),
  ('si', 'if', 'conjunction', 'Si llueve, no saldremos.', 1, 0),
  ('me', 'to me/for me', 'pronoun', 'Me dio un regalo hermoso.', 1, 0),
  ('ya', 'already/now', 'adverb', 'Ya terminé mi trabajo.', 1, 0),
  ('ver', 'to see (irregular)', 'verb', 'Quiero ver esa película.', 1, 0),
  ('porque', 'because', 'conjunction', 'No fui porque estaba enfermo.', 1, 0),
  ('dar', 'to give (irregular)', 'verb', 'Te voy a dar un consejo.', 1, 0),
  ('cuando', 'when', 'conjunction', 'Te llamaré cuando llegue.', 1, 0),
  ('muy', 'very', 'adverb', 'Estoy muy feliz hoy.', 1, 0),
  ('sin', 'without', 'preposition', 'No puedo vivir sin ti.', 1, 0),
  ('vez', 'time/instance', 'noun', 'Es la primera vez que vengo aquí.', 1, 0),
  ('mucho', 'much/a lot', 'adjective', 'Hace mucho calor hoy.', 1, 0),
  ('saber', 'to know (irregular)', 'verb', 'No sé la respuesta.', 1, 0),
  ('qué', 'what', 'pronoun', '¿Qué quieres comer?', 1, 0),
  ('sobre', 'on/over/about', 'preposition', 'El libro está sobre la mesa.', 1, 0),
  ('mi', 'my', 'determiner', 'Mi coche es azul.', 1, 0),
  ('al', 'to the (a + el)', 'preposition', 'Voy al parque todos los días.', 1, 0),
  ('todo', 'all/every', 'adjective', 'Todo el mundo está aquí.', 1, 0),
  ('también', 'also/too', 'adverb', 'Yo también quiero un helado.', 1, 0),
  ('hasta', 'until/even', 'preposition', 'Trabajo hasta las cinco.', 1, 0),
  ('hay', 'there is/there are (from haber)', 'verb', 'Hay mucha gente en la fiesta.', 1, 0),
  ('año', 'year', 'noun', 'Feliz año nuevo.', 1, 0),
  ('dos', 'two', 'number', 'Tengo dos perros.', 1, 0),
  ('querer', 'to want/love (irregular e->ie)', 'verb', 'Quiero un café, por favor.', 1, 0),
  ('entre', 'between/among', 'preposition', 'El banco está entre la farmacia y el supermercado.', 1, 0),
  ('así', 'like this/so', 'adverb', 'Hazlo así, es más fácil.', 1, 0),
  ('primero', 'first', 'adjective', 'Es mi primer día de trabajo.', 1, 0),
  ('desde', 'from/since', 'preposition', 'Vivo aquí desde 2010.', 1, 0),
  ('grande', 'big/large', 'adjective', 'Su casa es muy grande.', 1, 0),
  ('nos', 'us/to us', 'pronoun', 'Nos gusta ir a la playa.', 1, 0),
  ('llegar', 'to arrive (regular -ar)', 'verb', 'El tren va a llegar pronto.', 1, 0),
  ('pasar', 'to pass/happen/spend time (regular -ar)', 'verb', '¿Qué pasa aquí?', 1, 0),
  ('sí', 'yes', 'adverb', 'Sí, quiero ir contigo.', 1, 0),
  ('ni', 'nor/neither', 'conjunction', 'No quiero ni té ni café.', 1, 0),
  ('nosotros', 'we/us', 'pronoun', 'Nosotros somos estudiantes.', 1, 0),
  ('tiempo', 'time/weather', 'noun', 'No tengo mucho tiempo libre.', 1, 0),
  ('mismo', 'same', 'adjective', 'Tenemos el mismo problema.', 1, 0),
  ('bien', 'well/fine', 'adverb', 'Todo está muy bien.', 1, 0),
  ('día', 'day', 'noun', '¡Buenos días!', 1, 0),
  ('donde', 'where', 'conjunction', '¿Dónde está el baño?', 1, 0),
  ('ahora', 'now', 'adverb', 'Tengo que irme ahora.', 1, 0),
  ('poco', 'little/few', 'adjective', 'Tengo poco dinero en efectivo.', 1, 0),
  ('cada', 'each/every', 'adjective', 'Leo un libro cada mes.', 1, 0),
  ('vida', 'life', 'noun', 'La vida es hermosa.', 1, 0),
  ('entonces', 'then/so', 'adverb', 'Entonces, ¿qué hacemos?', 1, 0),
  ('menos', 'less/fewer', 'adverb', 'Cuesta menos de diez euros.', 1, 0),
  ('nuevo', 'new', 'adjective', 'Tengo un coche nuevo.', 1, 0),
  ('solo/solamente', 'only/just', 'adverb', 'Solo quiero un vaso de agua.', 1, 0),
  ('tan', 'so/as', 'adverb', 'Es tan alto como su padre.', 1, 0),
  ('cosa', 'thing', 'noun', '¿Qué es esa cosa?', 1, 0),
  ('parte', 'part/portion', 'noun', 'Leí la primera parte del libro.', 1, 0),
  ('después', 'after/later', 'adverb', 'Te llamaré después de la cena.', 1, 0),
  ('alguno/algún', 'some/someone', 'adjective', '¿Tienes algún problema?', 1, 0),
  ('siempre', 'always', 'adverb', 'Siempre llego tarde.', 1, 0),
  ('creer', 'to believe/think (regular -er)', 'verb', 'Creo que va a llover.', 1, 0),
  ('encontrar', 'to find (irregular o->ue)', 'verb', 'No puedo encontrar mis llaves.', 1, 0),
  ('forma', 'form/shape/way', 'noun', 'Esta es la mejor forma de hacerlo.', 1, 0),
  ('nada', 'nothing/anything', 'pronoun', 'No hay nada en la nevera.', 1, 0),
  ('hombre', 'man', 'noun', 'Ese hombre es mi tío.', 1, 0),
  ('bien', 'good/fine', 'adjective', 'Está bien.', 1, 0),
  ('mujer', 'woman', 'noun', 'Esa mujer es muy inteligente.', 1, 0),
  ('algo', 'something/anything', 'pronoun', 'Necesito algo para comer.', 1, 0),
  ('parecer', 'to seem/appear (irregular)', 'verb', 'Me parece una buena idea.', 1, 0),
  ('queda', 'remains/is located', 'verb', 'La tienda queda cerca de aquí.', 1, 0),
  ('hablar', 'to talk/speak (regular -ar)', 'verb', 'Quiero hablar contigo.', 2, 0),
  ('tomar', 'to take/drink (regular -ar)', 'verb', 'Voy a tomar un café.', 2, 0),
  ('trabajar', 'to work (regular -ar)', 'verb', 'Trabajo todos los días.', 2, 0),
  ('esperar', 'to wait/hope (regular -ar)', 'verb', 'Espero que tengas un buen día.', 2, 0),
  ('mirar', 'to look/watch (regular -ar)', 'verb', 'Mira ese pájaro.', 2, 0),
  ('comprar', 'to buy (regular -ar)', 'verb', 'Quiero comprar un libro.', 2, 0),
  ('necesitar', 'to need (regular -ar)', 'verb', 'Necesito más tiempo.', 2, 0),
  ('terminar', 'to finish (regular -ar)', 'verb', 'Ya terminé mi tarea.', 2, 0),
  ('explicar', 'to explain (regular -ar)', 'verb', '¿Puedes explicar esto?', 2, 0),
  ('preguntar', 'to ask (regular -ar)', 'verb', 'Quiero hacerte una pregunta.', 2, 0),
  ('estudiar', 'to study (regular -ar)', 'verb', 'Estudio español en la escuela.', 2, 0),
  ('escuchar', 'to listen (regular -ar)', 'verb', 'Escucha esta canción.', 2, 0),
  ('viajar', 'to travel (regular -ar)', 'verb', 'Me encanta viajar.', 2, 0),
  ('llamar', 'to call (regular -ar)', 'verb', 'Te voy a llamar mañana.', 2, 0),
  ('ayudar', 'to help (regular -ar)', 'verb', '¿Me puedes ayudar?', 2, 0),
  ('enseñar', 'to teach/show (regular -ar)', 'verb', 'Ella me va a enseñar a bailar.', 2, 0),
  ('ganar', 'to win/earn (regular -ar)', 'verb', 'Nuestro equipo ganó el partido.', 2, 0),
  ('comer', 'to eat (regular -er)', 'verb', 'Me gusta comer pollo.', 2, 0),
  ('beber', 'to drink (regular -er)', 'verb', 'Vamos a beber unas cervezas.', 2, 0),
  ('comprender', 'to understand (regular -er)', 'verb', 'No comprendo.', 2, 0),
  ('aprender', 'to learn (regular -er)', 'verb', 'Quiero aprender más español.', 2, 0),
  ('vender', 'to sell (regular -er)', 'verb', 'Él vende coches usados.', 2, 0),
  ('leer', 'to read (regular -er)', 'verb', 'Leo un libro cada semana.', 2, 0),
  ('correr', 'to run (regular -er)', 'verb', 'Corro en el parque todas las mañanas.', 2, 0),
  ('esconder', 'to hide (regular -er)', 'verb', 'No te escondas.', 2, 0),
  ('prometer', 'to promise (regular -er)', 'verb', 'Te prometo que iré.', 2, 0),
  ('romper', 'to break (regular -er, irreg part)', 'verb', '¡No rompas el vaso!', 2, 0),
  ('responder', 'to answer (regular -er)', 'verb', 'Responde a mi pregunta.', 2, 0),
  ('creer', 'to believe/think (regular -er)', 'verb', 'Creo en ti.', 2, 0),
  ('vivir', 'to live (regular -ir)', 'verb', 'Vivo en Barcelona.', 2, 0),
  ('escribir', 'to write (regular -ir, irreg part)', 'verb', 'Ella escribe poemas.', 2, 0),
  ('abrir', 'to open (regular -ir, irreg part)', 'verb', 'Abre la ventana, por favor.', 2, 0),
  ('recibir', 'to receive (regular -ir)', 'verb', 'Recibí tu carta.', 2, 0),
  ('decidir', 'to decide (regular -ir)', 'verb', 'Tienes que decidir pronto.', 2, 0),
  ('subir', 'to go up/climb (regular -ir)', 'verb', 'Sube las escaleras.', 2, 0),
  ('sufrir', 'to suffer (regular -ir)', 'verb', 'No quiero sufrir más.', 2, 0),
  ('ocurrir', 'to happen/occur (regular -ir)', 'verb', 'Ese accidente ocurrió ayer.', 2, 0),
  ('añadir', 'to add (regular -ir)', 'verb', 'Añade un poco de sal.', 2, 0),
  ('ser', 'to be (irregular)', 'verb', 'Mi padre es alto.', 3, 0),
  ('estar', 'to be (irregular)', 'verb', 'Estoy en casa.', 3, 0),
  ('tener', 'to have (irregular)', 'verb', 'Tengo dos hermanos.', 3, 0),
  ('hacer', 'to do/to make (irregular)', 'verb', '¿Qué estás haciendo?', 3, 0),
  ('poder', 'to be able to/can (irregular o->ue)', 'verb', '¿Puedes ayudarme?', 3, 0),
  ('decir', 'to say/to tell (irregular e->i)', 'verb', 'Dime la verdad.', 3, 0),
  ('ir', 'to go (irregular)', 'verb', 'Vamos al cine esta noche.', 3, 0),
  ('ver', 'to see (irregular)', 'verb', 'Quiero ver la televisión.', 3, 0),
  ('dar', 'to give (irregular)', 'verb', 'Te doy mi palabra.', 3, 0),
  ('saber', 'to know facts/how to (irregular)', 'verb', 'Lo sé todo.', 3, 0),
  ('querer', 'to want/to love (irregular e->ie)', 'verb', 'Te quiero mucho.', 3, 0),
  ('pensar', 'to think (irregular e->ie)', 'verb', 'Pienso que es una buena idea.', 3, 0),
  ('encontrar', 'to find (irregular o->ue)', 'verb', 'No la encuentro.', 3, 0),
  ('volver', 'to return/go back (irregular o->ue)', 'verb', 'Vuelvo a las seis.', 3, 0),
  ('salir', 'to leave/go out (irregular)', 'verb', 'Salgo con mis amigos.', 3, 0),
  ('conocer', 'to know people/places (irregular)', 'verb', 'Conozco bien esa ciudad.', 3, 0),
  ('empezar', 'to begin/start (irregular e->ie)', 'verb', 'La película empieza ahora.', 3, 0),
  ('entender', 'to understand (irregular e->ie)', 'verb', 'No entiendo el problema.', 3, 0),
  ('pedir', 'to ask for/request (irregular e->i)', 'verb', 'Voy a pedir una pizza.', 3, 0),
  ('sentir', 'to feel/regret (irregular e->ie)', 'verb', 'Lo siento mucho.', 3, 0),
  ('dormir', 'to sleep (irregular o->ue)', 'verb', 'Quiero dormir ahora.', 3, 0),
  ('seguir', 'to follow/continue (irregular e->i)', 'verb', 'Sígueme, por favor.', 3, 0),
  ('venir', 'to come (irregular e->ie)', 'verb', 'Ven aquí.', 3, 0),
  ('traer', 'to bring (irregular)', 'verb', '¿Me traes un vaso de agua?', 3, 0),
  ('poner', 'to put/place (irregular)', 'verb', 'Pon el libro en la mesa.', 3, 0),
  ('jugar', 'to play (irregular u->ue)', 'verb', 'Jugamos al fútbol los domingos.', 3, 0),
  ('cerrar', 'to close (irregular e->ie)', 'verb', 'Cierra la puerta.', 3, 0),
  ('recordar', 'to remember/remind (irregular o->ue)', 'verb', 'Recuerdo tu cara.', 3, 0),
  ('mostrar', 'to show (irregular o->ue)', 'verb', 'Enséñame tu nuevo coche.', 3, 0),
  ('perder', 'to lose/miss (irregular e->ie)', 'verb', 'No quiero perderte.', 3, 0),
  ('caer', 'to fall (irregular)', 'verb', 'Las hojas caen en otoño.', 3, 0),
  ('oír', 'to hear/listen (irregular)', 'verb', 'No te oigo bien.', 3, 0),
  ('conseguir', 'to get/obtain (irregular e->i)', 'verb', 'Consiguió un nuevo trabajo.', 3, 0),
  ('servir', 'to serve (irregular e->i)', 'verb', 'Esta herramienta no sirve.', 3, 0),
  ('repetir', 'to repeat (irregular e->i)', 'verb', 'Por favor, repita la pregunta.', 3, 0),
  ('reír', 'to laugh (irregular e->i)', 'verb', 'Me hace reír.', 3, 0),
  ('costar', 'to cost (irregular o->ue)', 'verb', '¿Cuánto cuesta este coche?', 3, 0),
  ('medir', 'to measure (irregular e->i)', 'verb', 'Mide dos metros de altura.', 3, 0),
  ('bueno/buen', 'good', 'adjective', 'Es un buen perro.', 4, 0),
  ('malo/mal', 'bad', 'adjective', 'Hace mal tiempo.', 4, 0),
  ('grande/gran', 'big', 'adjective', 'Es un gran problema.', 4, 0),
  ('pequeño', 'small', 'adjective', 'Este coche es muy pequeño.', 4, 0),
  ('nuevo', 'new', 'adjective', 'Mi coche es nuevo.', 4, 0),
  ('viejo', 'old', 'adjective', 'Tengo un coche viejo.', 4, 0),
  ('alto', 'tall/high', 'adjective', 'Mi hermano es muy alto.', 4, 0),
  ('bajo', 'short/low', 'adjective', 'El techo es muy bajo.', 4, 0),
  ('largo', 'long', 'adjective', 'El camino es largo.', 4, 0),
  ('corto', 'short (length)', 'adjective', 'El pelo de Juan es corto.', 4, 0),
  ('fácil', 'easy', 'adjective', 'El examen fue muy fácil.', 4, 0),
  ('difícil', 'hard/difficult', 'adjective', 'Aprender chino es difícil.', 4, 0),
  ('feliz', 'happy', 'adjective', 'Estoy muy feliz hoy.', 4, 0),
  ('triste', 'sad', 'adjective', 'La película fue muy triste.', 4, 0),
  ('rápido', 'fast/quick', 'adjective', 'Corre muy rápido.', 4, 0),
  ('lento', 'slow', 'adjective', 'Esta tortuga es lenta.', 4, 0),
  ('caliente', 'hot', 'adjective', 'El café está muy caliente.', 4, 0),
  ('frío', 'cold', 'adjective', 'Hace mucho frío hoy.', 4, 0),
  ('bonito', 'pretty/beautiful', 'adjective', 'Qué vestido tan bonito.', 4, 0),
  ('feo', 'ugly', 'adjective', 'Ese edificio es muy feo.', 4, 0),
  ('caro', 'expensive', 'adjective', 'Ese coche es demasiado caro.', 4, 0),
  ('barato', 'cheap', 'adjective', 'Compré esto muy barato.', 4, 0),
  ('rico', 'rich/delicious', 'adjective', 'La comida está muy rica.', 4, 0),
  ('pobre', 'poor', 'adjective', 'Ellos son de una familia pobre.', 4, 0),
  ('fuerte', 'strong', 'adjective', 'Él es muy fuerte.', 4, 0),
  ('débil', 'weak', 'adjective', 'Me siento un poco débil.', 4, 0),
  ('joven', 'young', 'adjective', 'Es demasiado joven para conducir.', 4, 0),
  ('mayor', 'older/larger', 'adjective', 'Mi hermano mayor vive en Madrid.', 4, 0),
  ('mejor', 'better/best', 'adjective', 'Él es mi mejor amigo.', 4, 0),
  ('peor', 'worse/worst', 'adjective', 'Fue el peor día de mi vida.', 4, 0),
  ('aquí', 'here', 'adverb', 'Ven aquí, por favor.', 4, 0),
  ('allí/allá', 'there', 'adverb', 'Mi casa está allí.', 4, 0),
  ('cerca', 'close/near', 'adverb', 'Vivo cerca de la escuela.', 4, 0),
  ('lejos', 'far', 'adverb', 'El supermercado está lejos.', 4, 0),
  ('antes', 'before', 'adverb', 'Tienes que terminar antes de mañana.', 4, 0),
  ('después', 'after/afterward', 'adverb', 'Vamos a comer después.', 4, 0),
  ('siempre', 'always', 'adverb', 'Siempre me levanto temprano.', 4, 0),
  ('nunca', 'never', 'adverb', 'Nunca he estado en España.', 4, 0),
  ('pronto', 'soon', 'adverb', 'Te veré muy pronto.', 4, 0),
  ('tarde', 'late/afternoon', 'adverb', 'Llegué demasiado tarde al tren.', 4, 0),
  ('temprano', 'early', 'adverb', 'Mañana me levantaré temprano.', 4, 0),
  ('mucho', 'much/a lot/very', 'adverb', 'Trabajo mucho todos los días.', 4, 0),
  ('poco', 'little/not much', 'adverb', 'Queda poco tiempo.', 4, 0),
  ('bastante', 'enough/quite', 'adverb', 'Es bastante inteligente.', 4, 0),
  ('demasiado', 'too much/too', 'adverb', 'Comí demasiado pastel.', 4, 0),
  ('solo/solamente', 'only/just', 'adverb', 'Solo quiero un café.', 4, 0),
  ('todavía/aún', 'still/yet', 'adverb', 'Todavía no he terminado.', 4, 0),
  ('ya', 'already/now/yet', 'adverb', 'Ya son las diez y media.', 4, 0),
  ('también', 'also/too', 'adverb', 'Yo también hablo inglés.', 4, 0),
  ('tampoco', 'neither/not either', 'adverb', 'Él no sabe, y yo tampoco.', 4, 0),
  ('así', 'like this/so/thus', 'adverb', 'Lo hice así.', 4, 0),
  ('bien', 'well', 'adverb', 'Cantas muy bien.', 4, 0),
  ('mal', 'badly/poorly', 'adverb', 'El coche funciona mal.', 4, 0),
  ('quizás/tal vez', 'maybe/perhaps', 'adverb', 'Quizás llueva mañana.', 4, 0),
  ('seguro', 'sure/safe', 'adjective', 'Estoy seguro de que vendrá.', 4, 0),
  ('uno', 'one', 'number', 'Solo quiero un helado.', 5, 0),
  ('dos', 'two', 'number', 'Tengo dos hermanos.', 5, 0),
  ('tres', 'three', 'number', 'Hay tres libros en la mesa.', 5, 0),
  ('cuatro', 'four', 'number', 'Las cuatro de la tarde.', 5, 0),
  ('cinco', 'five', 'number', 'Cinco minutos más.', 5, 0),
  ('seis', 'six', 'number', 'Seis personas vinieron a la cena.', 5, 0),
  ('siete', 'seven', 'number', 'Trabajo los siete días de la semana.', 5, 0),
  ('ocho', 'eight', 'number', 'Duermo ocho horas diarias.', 5, 0),
  ('nueve', 'nine', 'number', 'Nueve de cada diez dentistas lo recomiendan.', 5, 0),
  ('diez', 'ten', 'number', 'Diez euros, por favor.', 5, 0),
  ('veinte', 'twenty', 'number', 'Cuesta veinte dólares.', 5, 0),
  ('treinta', 'thirty', 'number', 'Tengo treinta años.', 5, 0),
  ('cuarenta', 'forty', 'number', 'Somos cuarenta en la clase.', 5, 0),
  ('cincuenta', 'fifty', 'number', 'El abrigo cuesta cincuenta euros.', 5, 0),
  ('cien', 'hundred', 'number', 'Más de cien personas asistieron.', 5, 0),
  ('primero', 'first', 'adjective', 'Mi primera lección.', 5, 0),
  ('segundo', 'second', 'adjective', 'El segundo piso.', 5, 0),
  ('tercero', 'third', 'adjective', 'Vive en el tercer piso.', 5, 0),
  ('lunes', 'Monday', 'noun', 'Nos vemos el lunes.', 5, 0),
  ('martes', 'Tuesday', 'noun', 'El martes tengo una reunión.', 5, 0),
  ('miércoles', 'Wednesday', 'noun', 'El miércoles es mi cumpleaños.', 5, 0),
  ('jueves', 'Thursday', 'noun', 'Salimos este jueves.', 5, 0),
  ('viernes', 'Friday', 'noun', 'Por fin es viernes.', 5, 0),
  ('sábado', 'Saturday', 'noun', 'El sábado vamos a la playa.', 5, 0),
  ('domingo', 'Sunday', 'noun', 'Los domingos descanso.', 5, 0),
  ('enero', 'January', 'noun', 'Hace frío en enero.', 5, 0),
  ('febrero', 'February', 'noun', 'Mi cumpleaños es en febrero.', 5, 0),
  ('marzo', 'March', 'noun', 'La primavera empieza en marzo.', 5, 0),
  ('abril', 'April', 'noun', 'Lluvias de abril.', 5, 0),
  ('mayo', 'May', 'noun', 'Mi madre nació en mayo.', 5, 0),
  ('junio', 'June', 'noun', 'Terminamos las clases en junio.', 5, 0),
  ('julio', 'July', 'noun', 'Nos vamos de vacaciones en julio.', 5, 0),
  ('agosto', 'August', 'noun', 'Hace mucho calor en agosto.', 5, 0),
  ('septiembre', 'September', 'noun', 'En septiembre vuelvo al trabajo.', 5, 0),
  ('octubre', 'October', 'noun', 'Halloween es en octubre.', 5, 0),
  ('noviembre', 'November', 'noun', 'Noviembre es un mes frío.', 5, 0),
  ('diciembre', 'December', 'noun', 'Navidad es en diciembre.', 5, 0),
  ('hoy', 'today', 'adverb', 'Hoy es un buen día.', 5, 0),
  ('ayer', 'yesterday', 'adverb', 'Ayer llovió mucho.', 5, 0),
  ('mañana', 'tomorrow/morning', 'noun', 'Mañana será otro día.', 5, 0),
  ('noche', 'night', 'noun', 'Buenas noches.', 5, 0),
  ('tarde', 'afternoon', 'noun', 'Buenas tardes.', 5, 0),
  ('semana', 'week', 'noun', 'Nos vemos la próxima semana.', 5, 0),
  ('mes', 'month', 'noun', 'El próximo mes viajo a España.', 5, 0),
  ('año', 'year', 'noun', 'Feliz año nuevo.', 5, 0),
  ('hora', 'hour', 'noun', 'Tienes una hora para terminar.', 5, 0),
  ('minuto', 'minute', 'noun', 'Dame un minuto.', 5, 0),
  ('segundo', 'second', 'noun', 'Espera un segundo.', 5, 0),
  ('reloj', 'clock/watch', 'noun', 'Mi reloj está roto.', 5, 0),
  ('vez', 'time/instance', 'noun', 'Es la primera vez que vengo.', 5, 0),
  ('siempre', 'always', 'adverb', 'Siempre llego a tiempo.', 5, 0),
  ('nunca', 'never', 'adverb', 'Nunca bebo alcohol.', 5, 0),
  ('próximo', 'next', 'adjective', 'El próximo tren sale a las seis.', 5, 0),
  ('pasado', 'past/last', 'adjective', 'El fin de semana pasado estuve enfermo.', 5, 0),
  ('ahora', 'now', 'adverb', 'Tienes que venir ahora.', 5, 0),
  ('ya', 'already/now', 'adverb', 'Ya son las diez.', 5, 0),
  ('todavía', 'still/yet', 'adverb', 'Todavía estoy trabajando.', 5, 0),
  ('hombre', 'man', 'noun', 'Ese hombre es muy alto.', 6, 0),
  ('mujer', 'woman', 'noun', 'Aquella mujer es mi profesora.', 6, 0),
  ('niño/niña', 'boy/girl', 'noun', 'Los niños juegan en el parque.', 6, 0),
  ('padre', 'father', 'noun', 'Mi padre es médico.', 6, 0),
  ('madre', 'mother', 'noun', 'Mi madre cocina muy bien.', 6, 0),
  ('hermano/hermana', 'brother/sister', 'noun', 'Tengo un hermano menor.', 6, 0),
  ('hijo/hija', 'son/daughter', 'noun', 'Ellas son mis hijas.', 6, 0),
  ('abuelo/abuela', 'grandfather/grandmother', 'noun', 'Mis abuelos viven en el campo.', 6, 0),
  ('tío/tía', 'uncle/aunt', 'noun', 'Mi tía me compró un regalo.', 6, 0),
  ('pronto/prima', 'cousin', 'noun', 'Mis primos vienen esta tarde.', 6, 0),
  ('amigo/amiga', 'friend', 'noun', 'Él es mi mejor amigo.', 6, 0),
  ('novio/novia', 'boyfriend/girlfriend', 'noun', 'Ella es mi novia.', 6, 0),
  ('esposo/esposa', 'husband/wife', 'noun', 'Su esposo trabaja en un banco.', 6, 0),
  ('familia', 'family', 'noun', 'Mi familia es muy grande.', 6, 0),
  ('persona', 'person', 'noun', 'Ella es una buena persona.', 6, 0),
  ('gente', 'people', 'noun', 'Hay mucha gente en la calle.', 6, 0),
  ('señor/señora', 'Mr./Mrs.', 'noun', 'El señor García está aquí.', 6, 0),
  ('casa', 'house/home', 'noun', 'Vivo en una casa blanca.', 6, 0),
  ('apartamento', 'apartment', 'noun', 'Mi apartamento es pequeño.', 6, 0),
  ('habitación', 'room/bedroom', 'noun', 'Mi habitación está limpia.', 6, 0),
  ('baño', 'bathroom', 'noun', '¿Dónde está el baño?', 6, 0),
  ('cocina', 'kitchen', 'noun', 'La cocina huele muy bien.', 6, 0),
  ('sala', 'living room', 'noun', 'Vemos la televisión en la sala.', 6, 0),
  ('puerta', 'door', 'noun', 'Cierra la puerta, por favor.', 6, 0),
  ('ventana', 'window', 'noun', 'Abre la ventana, hace calor.', 6, 0),
  ('mesa', 'table', 'noun', 'La comida está en la mesa.', 6, 0),
  ('silla', 'chair', 'noun', 'Por favor, siéntate en esta silla.', 6, 0),
  ('cama', 'bed', 'noun', 'Estoy cansado, me voy a la cama.', 6, 0),
  ('mueble', 'piece of furniture', 'noun', 'Necesitamos muebles nuevos.', 6, 0),
  ('televisión', 'television', 'noun', 'Están viendo la televisión.', 6, 0),
  ('radio', 'radio', 'noun', 'Me gusta escuchar la radio.', 6, 0),
  ('teléfono', 'phone/telephone', 'noun', 'Sonó el teléfono.', 6, 0),
  ('ropa', 'clothes/clothing', 'noun', 'Tengo que comprar ropa nueva.', 6, 0),
  ('camisa', 'shirt', 'noun', 'Llevo una camisa azul.', 6, 0),
  ('pantalones', 'pants/trousers', 'noun', 'Estos pantalones son muy grandes.', 6, 0),
  ('zapato', 'shoe', 'noun', 'Me gustan tus zapatos nuevos.', 6, 0),
  ('vestido', 'dress', 'noun', 'Lleva un vestido rojo.', 6, 0),
  ('abrigo', 'coat', 'noun', 'Ponte el abrigo, hace frío.', 6, 0),
  ('sombrero', 'hat', 'noun', 'Me gusta tu sombrero.', 6, 0),
  ('gafas', 'glasses', 'noun', 'No puedo ver sin mis gafas.', 6, 0),
  ('agua', 'water', 'noun', 'Un vaso de agua, por favor.', 7, 0),
  ('comida', 'food/meal', 'noun', 'La comida está servida.', 7, 0),
  ('pan', 'bread', 'noun', 'Necesito comprar pan.', 7, 0),
  ('carne', 'meat', 'noun', 'No como carne, soy vegetariano.', 7, 0),
  ('pescado', 'fish', 'noun', 'Hoy cenamos pescado.', 7, 0),
  ('pollo', 'chicken', 'noun', 'El pollo asado huele bien.', 7, 0),
  ('queso', 'cheese', 'noun', 'Me encantan los macarrones con queso.', 7, 0),
  ('huevo', 'egg', 'noun', 'Desayuno dos huevos todos los días.', 7, 0),
  ('fruta', 'fruit', 'noun', 'Debes comer más fruta.', 7, 0),
  ('manzana', 'apple', 'noun', 'Una manzana al día.', 7, 0),
  ('naranja', 'orange', 'noun', 'Quiero un zumo de naranja.', 7, 0),
  ('plátano', 'banana', 'noun', 'Los monos comen plátanos.', 7, 0),
  ('tomate', 'tomato', 'noun', 'Ensalada de tomate y lechuga.', 7, 0),
  ('cebolla', 'onion', 'noun', 'Lloré cortando la cebolla.', 7, 0),
  ('patata', 'potato', 'noun', 'Tortilla de patatas, por favor.', 7, 0),
  ('arroz', 'rice', 'noun', 'Me gusta el arroz blanco.', 7, 0),
  ('sal', 'salt', 'noun', '¿Me pasas la sal?', 7, 0),
  ('azúcar', 'sugar', 'noun', 'Un café sin azúcar.', 7, 0),
  ('aceite', 'oil', 'noun', 'Aceite de oliva español.', 7, 0),
  ('leche', 'milk', 'noun', 'Leche fría o caliente.', 7, 0),
  ('café', 'coffee', 'noun', 'Necesito un café fuerte.', 7, 0),
  ('té', 'tea', 'noun', 'Me gusta el té verde.', 7, 0),
  ('vino', 'wine', 'noun', 'Una botella de vino tinto.', 7, 0),
  ('cerveza', 'beer', 'noun', 'Dos cervezas frías, por favor.', 7, 0),
  ('desayuno', 'breakfast', 'noun', '¿Qué hay para el desayuno?', 7, 0),
  ('almuerzo', 'lunch', 'noun', 'La hora del almuerzo es a la una.', 7, 0),
  ('cena', 'dinner', 'noun', '¿Qué vamos a cenar?', 7, 0),
  ('viaje', 'trip/journey', 'noun', '¡Buen viaje!', 7, 0),
  ('coche', 'car', 'noun', 'Voy en coche al trabajo.', 7, 0),
  ('autobús', 'bus', 'noun', 'El autobús llega en cinco minutos.', 7, 0),
  ('tren', 'train', 'noun', 'El tren sale de la vía tres.', 7, 0),
  ('avión', 'airplane', 'noun', 'Tengo miedo a volar en avión.', 7, 0),
  ('bicicleta', 'bicycle', 'noun', 'Me gusta pasear en bicicleta.', 7, 0),
  ('calle', 'street', 'noun', 'Vivo en la calle mayor.', 7, 0),
  ('camino', 'road/path', 'noun', 'Este camino va al lago.', 7, 0),
  ('estación', 'station', 'noun', '¿Dónde está la estación de tren?', 7, 0),
  ('aeropuerto', 'airport', 'noun', 'Voy al aeropuerto a recogerla.', 7, 0),
  ('billete', 'ticket/bill', 'noun', 'Un billete de ida y vuelta.', 7, 0),
  ('hotel', 'hotel', 'noun', 'Nos alojamos en un hotel céntrico.', 7, 0),
  ('restaurante', 'restaurant', 'noun', 'Conozco un restaurante muy bueno.', 7, 0),
  ('ciudad', 'city', 'noun', 'Madrid es una ciudad hermosa.', 7, 0),
  ('pueblo', 'town/village', 'noun', 'Crecí en un pueblo pequeño.', 7, 0),
  ('país', 'country', 'noun', 'España es un país de Europa.', 7, 0),
  ('mundo', 'world', 'noun', 'Quiero viajar por todo el mundo.', 7, 0),
  ('playa', 'beach', 'noun', 'Vamos a la playa este verano.', 7, 0),
  ('mar', 'sea', 'noun', 'El mar está muy tranquilo hoy.', 7, 0),
  ('montaña', 'mountain', 'noun', 'Nos fuimos de excursión a la montaña.', 7, 0),
  ('cabeza', 'head', 'noun', 'Me duele la cabeza.', 8, 0),
  ('mano', 'hand', 'noun', 'Dame la mano.', 8, 0),
  ('ojo', 'eye', 'noun', 'Ella tiene los ojos azules.', 8, 0),
  ('boca', 'mouth', 'noun', 'Cállate la boca.', 8, 0),
  ('brazo', 'arm', 'noun', 'Se rompió el brazo.', 8, 0),
  ('pierna', 'leg', 'noun', 'Me duelen las piernas de tanto correr.', 8, 0),
  ('pie', 'foot', 'noun', 'Tengo frío en los pies.', 8, 0),
  ('pelo', 'hair', 'noun', 'Tiene el pelo largo.', 8, 0),
  ('cara', 'face', 'noun', 'Lávate la cara.', 8, 0),
  ('espalda', 'back', 'noun', 'Me duele mucho la espalda.', 8, 0),
  ('estómago', 'stomach', 'noun', 'Tengo dolor de estómago.', 8, 0),
  ('corazón', 'heart', 'noun', 'Mi corazón late muy rápido.', 8, 0),
  ('sangre', 'blood', 'noun', 'Sale mucha sangre.', 8, 0),
  ('hueso', 'bone', 'noun', 'El perro está masticando un hueso.', 8, 0),
  ('piel', 'skin', 'noun', 'Tengo la piel seca.', 8, 0),
  ('dedo', 'finger/toe', 'noun', 'Me corté el dedo.', 8, 0),
  ('enfermo', 'sick', 'adjective', 'Me siento muy enfermo.', 8, 0),
  ('dolor', 'pain', 'noun', 'Tengo un dolor terrible.', 8, 0),
  ('médico', 'doctor', 'noun', 'Tienes que ir al médico.', 8, 0),
  ('hospital', 'hospital', 'noun', 'Mi abuela está en el hospital.', 8, 0),
  ('farmacia', 'pharmacy', 'noun', 'Necesito ir a la farmacia.', 8, 0),
  ('medicina', 'medicine', 'noun', 'Tómate la medicina.', 8, 0),
  ('píldora', 'pill', 'noun', 'Una píldora para dormir.', 8, 0),
  ('fiebre', 'fever', 'noun', 'El niño tiene fiebre alta.', 8, 0),
  ('tos', 'cough', 'noun', 'Esa tos suena muy mal.', 8, 0),
  ('gripe', 'flu', 'noun', 'Hay epidemia de gripe.', 8, 0),
  ('resfriado', 'cold (illness)', 'noun', 'He cogido un buen resfriado.', 8, 0),
  ('accidente', 'accident', 'noun', 'Vi un accidente de coche.', 8, 0),
  ('ayuda', 'help', 'noun', '¡Necesito ayuda!', 8, 0),
  ('policía', 'police', 'noun', '¡Llama a la policía!', 8, 0),
  ('bombero', 'firefighter', 'noun', 'Los bomberos apagaron el fuego.', 8, 0),
  ('peligro', 'danger', 'noun', '¡Peligro de muerte!', 8, 0),
  ('cuidado', 'care/caution', 'noun', '¡Ten cuidado!', 8, 0),
  ('seguro', 'safe/sure', 'adjective', 'Estás seguro aquí.', 8, 0),
  ('urgencia', 'emergency', 'noun', 'Es una urgencia médica.', 8, 0),
  ('salud', 'health', 'noun', 'El dinero no da la salud.', 8, 0),
  ('vida', 'life', 'noun', 'Me salvó la vida.', 8, 0),
  ('muerte', 'death', 'noun', 'Vida y muerte.', 8, 0),
  ('trabajo', 'work/job', 'noun', 'Busco trabajo.', 10, 0),
  ('empresa', 'company', 'noun', 'Trabajo en una gran empresa.', 10, 0),
  ('oficina', 'office', 'noun', 'Mi oficina está en el centro.', 10, 0),
  ('jefe / jefa', 'boss', 'noun', 'Mi jefe es muy estricto.', 10, 0),
  ('dinero', 'money', 'noun', 'No tengo dinero para eso.', 10, 0),
  ('banco', 'bank', 'noun', 'Tengo que ir al banco hoy.', 10, 0),
  ('precio', 'price', 'noun', '¿Cuál es el precio?', 10, 0),
  ('mercado', 'market', 'noun', 'Compramos verduras en el mercado.', 10, 0),
  ('tienda', 'store/shop', 'noun', 'Esa tienda cierra a las nueve.', 10, 0),
  ('negocio', 'business', 'noun', 'Tienen un negocio familiar.', 10, 0),
  ('cliente', 'customer/client', 'noun', 'El cliente siempre tiene la razón.', 10, 0),
  ('computadora/ordenador', 'computer', 'noun', 'Uso la computadora todos los días.', 10, 0),
  ('pantalla', 'screen', 'noun', 'La pantalla de mi móvil está rota.', 10, 0),
  ('teclado', 'keyboard', 'noun', 'Necesito un teclado nuevo.', 10, 0),
  ('ratón/mouse', 'mouse', 'noun', 'El ratón no funciona.', 10, 0),
  ('internet', 'internet', 'noun', 'Se cayó la conexión a internet.', 10, 0),
  ('correo / email', 'mail/email', 'noun', 'Te enviaré un correo mañana.', 10, 0),
  ('mensaje', 'message', 'noun', 'Me dejó un mensaje de voz.', 10, 0),
  ('red', 'network/net', 'noun', 'La red wifi no funciona.', 10, 0),
  ('datos', 'data', 'noun', 'He perdido todos mis datos.', 10, 0),
  ('escuela', 'school', 'noun', 'Los niños están en la escuela.', 10, 0),
  ('universidad', 'university', 'noun', 'Estudia en la universidad.', 10, 0),
  ('clase', 'class', 'noun', 'Tengo clase a las diez.', 10, 0),
  ('profesor/profesora', 'teacher', 'noun', 'El profesor es muy aburrido.', 10, 0),
  ('estudiante/alumno', 'student', 'noun', 'Soy estudiante universitario.', 10, 0),
  ('libro', 'book', 'noun', 'Estoy leyendo un buen libro.', 10, 0),
  ('cuaderno', 'notebook', 'noun', 'Escríbelo en tu cuaderno.', 10, 0),
  ('lápiz', 'pencil', 'noun', '¿Me prestas un lápiz?', 10, 0),
  ('bolígrafo', 'pen', 'noun', 'Necesito un bolígrafo azul.', 10, 0),
  ('examen', 'exam/test', 'noun', 'Mañana tengo un examen importante.', 10, 0),
  ('pregunta', 'question', 'noun', 'Tengo una pregunta.', 10, 0),
  ('respuesta', 'answer', 'noun', 'No sé la respuesta.', 10, 0),
  ('ejemplo', 'example', 'noun', 'Por ejemplo, los gatos.', 10, 0),
  ('palabra', 'word', 'noun', '¿Qué significa esta palabra?', 10, 0),
  ('idioma', 'language', 'noun', 'El español es un idioma hermoso.', 10, 0),
  ('historia', 'history/story', 'noun', 'Me gusta la historia antigua.', 10, 0),
  ('ciencia', 'science', 'noun', 'La biociencia es el futuro.', 10, 0),
  ('arte', 'art', 'noun', 'Un museo de arte moderno.', 10, 0),
  ('música', 'music', 'noun', 'Escucho música mientras estudio.', 10, 0),
  ('canción', 'song', 'noun', 'Esa canción es mi favorita.', 10, 0),
  ('película', 'movie', 'noun', '¿Qué película vamos a ver?', 10, 0),
  ('juego', 'game', 'noun', 'Vamos a jugar un juego.', 10, 0),
  ('equipo', 'team/equipment', 'noun', 'Nuestro equipo ganó.', 10, 0),
  ('con', 'with', 'preposition', 'Lo hice con cuidado.', 9, 0),
  ('de', 'of/from', 'preposition', 'La casa de mi madre.', 9, 0),
  ('a', 'to/at', 'preposition', 'Voy a dormir.', 9, 0),
  ('en', 'in/on', 'preposition', 'Está en la caja.', 9, 0),
  ('por', 'for/by', 'preposition', 'Comprado por diez euros.', 9, 0),
  ('para', 'for/in order to', 'preposition', 'Es para ti.', 9, 0),
  ('sin', 'without', 'preposition', 'Un café sin leche.', 9, 0),
  ('sobre', 'about/on/over', 'preposition', 'Hablamos sobre política.', 9, 0),
  ('entre', 'between/among', 'preposition', 'Está entre tú y yo.', 9, 0),
  ('hasta', 'until/even', 'preposition', 'Trabajo hasta el viernes.', 9, 0),
  ('desde', 'from/since', 'preposition', 'Te espero desde ayer.', 9, 0),
  ('hacia', 'toward', 'preposition', 'Miró hacia la ventana.', 9, 0),
  ('contra', 'against', 'preposition', 'Jugamos contra ellos.', 9, 0),
  ('según', 'according to', 'preposition', 'Según las noticias, lloverá.', 9, 0),
  ('bajo', 'under', 'preposition', 'El perro está bajo la mesa.', 9, 0),
  ('ante', 'before/in the presence of', 'preposition', 'Temblaba ante el juez.', 9, 0),
  ('tras', 'after/behind', 'preposition', 'Corrió tras el ladrón.', 9, 0),
  ('durante', 'during', 'preposition', 'Llovió durante la noche.', 9, 0),
  ('mediante', 'by means of', 'preposition', 'Lo pagó mediante transferencia.', 9, 0),
  ('y/e', 'and', 'conjunction', 'Juan y María (Padre e hijo).', 9, 0),
  ('o/u', 'or', 'conjunction', '¿Té o café? (Siete u ocho).', 9, 0),
  ('pero', 'but', 'conjunction', 'Es tarde, pero me quedo.', 9, 0),
  ('sino', 'but rather', 'conjunction', 'No es azul, sino verde.', 9, 0),
  ('aunque', 'although/even though', 'conjunction', 'Saldré, aunque llueva.', 9, 0),
  ('porque', 'because', 'conjunction', 'Lloro porque estoy triste.', 9, 0),
  ('como', 'like/as/since', 'conjunction', 'Canta como un ángel.', 9, 0),
  ('si', 'if/whether', 'conjunction', 'Dime si quieres venir.', 9, 0),
  ('cuando', 'when', 'conjunction', 'Era joven cuando nos conocimos.', 9, 0),
  ('mientras', 'while', 'conjunction', 'Escucha música mientras estudia.', 9, 0),
  ('que', 'that/than', 'conjunction/pronoun', 'Quiero que vengas.', 9, 0),
  ('donde', 'where', 'conjunction/adverb', 'Vamos donde tú quieras.', 9, 0),
  ('quien', 'who/whom', 'pronoun', '¿Con quién fuiste?', 9, 0),
  ('cual', 'which/who', 'pronoun', 'Esta es la casa en la cual nací.', 9, 0),
  ('entonces', 'then', 'adverb/conjunction', 'Entonces, nos vamos.', 9, 0),
  ('luego', 'later/then', 'adverb', 'Voy al banco y luego a casa.', 9, 0),
  ('así', 'thus/so/this way', 'adverb', 'No lo hagas así.', 9, 0),
  ('también', 'also/too', 'adverb', 'Yo también tengo hambre.', 9, 0),
  ('tampoco', 'neither/not either', 'adverb', 'Yo tampoco sé.', 9, 0),
  ('ya', 'already/anymore', 'adverb', 'Ya no creo en eso.', 9, 0),
  ('todavía/aún', 'still/yet', 'adverb', '¿Todavía estás aquí?', 9, 0),
  ('además', 'besides/in addition', 'adverb', 'Además, es muy caro.', 9, 0),
  ('incluso', 'even/including', 'adverb/preposition', 'Incluso él lo sabe.', 9, 0),
  ('tal vez / quizás', 'maybe/perhaps', 'adverb', 'Quizás tengas razón.', 9, 0),
  ('siempre', 'always', 'adverb', 'Siempre dice la verdad.', 9, 0),
  ('nunca/jamás', 'never', 'adverb', 'Jamás olvidaré este día.', 9, 0),
  ('claro', 'of course/clear', 'adjective/adverb', '¡Claro que sí!', 9, 0),
  ('bueno', 'well.../good', 'adjective/interjection', 'Bueno, me voy.', 9, 0),
  ('pues', 'well/since', 'conjunction/interjection', 'Pues no lo sé.', 9, 0),
  ('hola', 'hello', 'greeting', '¡Hola, qué tal!', 9, 0),
  ('adiós', 'goodbye', 'greeting', '¡Adiós, hasta luego!', 9, 0),
  ('gracias', 'thank you', 'greeting', 'Muchas gracias por todo.', 9, 0),
  ('por favor', 'please', 'phrase', 'Un café, por favor.', 9, 0),
  ('lo siento', 'I''m sorry', 'phrase', 'Lo siento mucho.', 9, 0),
  ('perdón', 'excuse me/sorry', 'greeting', 'Perdón, me he equivocado.', 9, 0),
  ('de nada', 'you''re welcome', 'phrase', '-¡Gracias! -De nada.', 9, 0),
  ('vale', 'okay', 'phrase', 'Vale, nos vemos a las ocho.', 9, 0),
  ('feliz', 'happy', 'adjective', 'Ella siempre está feliz.', 4, 0),
  ('triste', 'sad', 'adjective', 'Hoy me siento un poco triste.', 4, 0),
  ('cansado', 'tired', 'adjective', 'Estoy muy cansado de trabajar.', 4, 0),
  ('enfermo', 'sick', 'adjective', 'No voy porque estoy enfermo.', 4, 0),
  ('sano', 'healthy', 'adjective', 'Comer fruta te mantiene sano.', 4, 0),
  ('fuerte', 'strong', 'adjective', 'Es un hombre muy fuerte.', 4, 0),
  ('débil', 'weak', 'adjective', 'Me siento débil.', 4, 0),
  ('inteligente', 'intelligent/smart', 'adjective', 'Mi hija es muy inteligente.', 4, 0),
  ('tonto', 'silly/dumb', 'adjective', 'No seas tonto.', 4, 0),
  ('rápido', 'fast/quick', 'adjective', 'Este coche es muy rápido.', 4, 0),
  ('lento', 'slow', 'adjective', 'El autobús va muy lento.', 4, 0),
  ('caro', 'expensive', 'adjective', 'Esa casa es demasiado cara.', 4, 0),
  ('barato', 'cheap', 'adjective', 'Encontré zapatos muy baratos.', 4, 0),
  ('limpio', 'clean', 'adjective', 'Mi habitación está limpia.', 4, 0),
  ('sucio', 'dirty', 'adjective', 'Tienes los zapatos sucios.', 4, 0),
  ('lleno', 'full', 'adjective', 'El cine estaba lleno.', 4, 0),
  ('vacío', 'empty', 'adjective', 'El vaso está vacío.', 4, 0),
  ('abierto', 'open', 'adjective', 'La puerta está abierta.', 4, 0),
  ('cerrado', 'closed', 'adjective', 'El museo está cerrado los lunes.', 4, 0),
  ('fácil', 'easy', 'adjective', 'El examen fue muy fácil.', 4, 0),
  ('difícil', 'difficult/hard', 'adjective', 'Aprender ruso es muy difícil.', 4, 0),
  ('posible', 'possible', 'adjective', 'Creo que es posible.', 4, 0),
  ('imposible', 'impossible', 'adjective', 'Eso es imposible de hacer.', 4, 0),
  ('seguro', 'sure/safe', 'adjective', 'Estoy seguro de que vendrá.', 4, 0),
  ('peligroso', 'dangerous', 'adjective', 'Conducir rápido es peligroso.', 4, 0),
  ('importante', 'important', 'adjective', 'Tenemos una reunión importante.', 4, 0),
  ('mismo', 'same', 'adjective', 'Tenemos el mismo coche.', 4, 0),
  ('distinto', 'different', 'adjective', 'Somos de países distintos.', 4, 0),
  ('único', 'only/unique', 'adjective', 'Es mi único hermano.', 4, 0),
  ('solo', 'alone/lonely', 'adjective', 'No me gusta estar solo.', 4, 0),
  ('próximo', 'next', 'adjective', 'Nos vemos la próxima semana.', 4, 0),
  ('último', 'last/final', 'adjective', 'Es la última vez que te lo digo.', 4, 0),
  ('anterior', 'previous', 'adjective', 'En la página anterior.', 4, 0),
  ('siguiente', 'following/next', 'adjective', 'Lea el siguiente párrafo.', 4, 0),
  ('cierto', 'true/certain', 'adjective', 'Eso no es cierto.', 4, 0),
  ('falso', 'false/fake', 'adjective', 'Las noticias eran falsas.', 4, 0),
  ('claro', 'clear/light', 'adjective', 'El agua está muy clara.', 4, 0),
  ('oscuro', 'dark', 'adjective', 'El cuarto está oscuro.', 4, 0),
  ('pesado', 'heavy', 'adjective', 'Esta caja es muy pesada.', 4, 0),
  ('ligero', 'light (weight)', 'adjective', 'Necesito equipaje ligero.', 4, 0),
  ('duro', 'hard', 'adjective', 'Este pan está muy duro.', 4, 0),
  ('suave', 'soft/smooth', 'adjective', 'Tiene la piel muy suave.', 4, 0),
  ('frío', 'cold', 'adjective', 'El invierno es frío.', 4, 0),
  ('caliente', 'hot', 'adjective', 'Ten cuidado, el plato está caliente.', 4, 0),
  ('seco', 'dry', 'adjective', 'Necesito un paño seco.', 4, 0),
  ('mojado', 'wet', 'adjective', 'Estoy mojado por la lluvia.', 4, 0),
  ('rico', 'rich/delicious', 'adjective', 'La comida está rica.', 4, 0),
  ('pobre', 'poor', 'adjective', 'Viven en un país pobre.', 4, 0),
  ('joven', 'young', 'adjective', 'Ella es muy joven aún.', 4, 0),
  ('viejo', 'old', 'adjective', 'Mi coche es viejo, pero funciona.', 4, 0),
  ('nuevo', 'new', 'adjective', 'Compré un libro nuevo.', 4, 0),
  ('alto', 'tall/high', 'adjective', 'El edificio es muy alto.', 4, 0),
  ('bajo', 'short/low', 'adjective', 'El techo de la casa es bajo.', 4, 0),
  ('largo', 'long', 'adjective', 'Tiene el pelo largo.', 4, 0),
  ('corto', 'short (length)', 'adjective', 'El camino más corto es por aquí.', 4, 0),
  ('ancho', 'wide/broad', 'adjective', 'Es un río muy ancho.', 4, 0),
  ('estrecho', 'narrow', 'adjective', 'La calle es muy estrecha.', 4, 0),
  ('bueno', 'good', 'adjective', 'Este es un buen amigo.', 4, 0),
  ('malo', 'bad', 'adjective', 'Hace muy mal tiempo.', 4, 0),
  ('mejor', 'better/best', 'adjective', 'Ella es la mejor estudiante.', 4, 0),
  ('peor', 'worse/worst', 'adjective', 'Fue el peor viaje de mi vida.', 4, 0),
  ('mayor', 'older/larger', 'adjective', 'Mi hermano mayor vive lejos.', 4, 0),
  ('menor', 'younger/smaller', 'adjective', 'Mi hermana menor va a la escuela.', 4, 0),
  ('hoy', 'today', 'adverb', 'Hoy hace un día precioso.', 5, 0),
  ('ayer', 'yesterday', 'adverb', 'Ayer trabajé mucho.', 5, 0),
  ('mañana', 'tomorrow/morning', 'noun', 'Mañana nos vemos.', 5, 0),
  ('ahora', 'now', 'adverb', 'Tienes que salir ahora mismo.', 5, 0),
  ('antes', 'before', 'adverb', 'Tuviste que decírmelo antes.', 5, 0),
  ('después', 'after/later', 'adverb', 'Te llamo después.', 5, 0),
  ('siempre', 'always', 'adverb', 'Siempre me acuesto tarde.', 5, 0),
  ('nunca', 'never', 'adverb', 'Nunca he estado allí.', 5, 0),
  ('pronto', 'soon', 'adverb', 'Espero verte pronto.', 5, 0),
  ('tarde', 'late/afternoon', 'adverb', 'Llegaste muy tarde al tren.', 5, 0),
  ('temprano', 'early', 'adverb', 'Me levanto muy temprano.', 5, 0),
  ('ya', 'already/now', 'adverb', 'Ya he terminado el trabajo.', 5, 0),
  ('todavía', 'still', 'adverb', '¿Todavía estás comiendo?', 5, 0),
  ('aún', 'still/yet', 'adverb', 'Aún no, espérate.', 5, 0),
  ('entonces', 'then', 'adverb', 'Entonces, ¿qué hacemos?', 5, 0),
  ('mientras', 'while', 'conjunction', 'Escucho música mientras estudio.', 5, 0),
  ('durante', 'during', 'preposition', 'Me dormí durante la película.', 5, 0),
  ('vez', 'time/instance', 'noun', 'Es la primera vez que vengo.', 5, 0),
  ('veces', 'times', 'noun', 'Fui allí muchas veces.', 5, 0),
  ('hora', 'hour/time', 'noun', '¿Qué hora es?', 5, 0),
  ('minuto', 'minute', 'noun', 'Faltan cinco minutos.', 5, 0),
  ('segundo', 'second', 'noun', 'Espera un segundo.', 5, 0),
  ('día', 'day', 'noun', 'Buenos días.', 5, 0),
  ('semana', 'week', 'noun', 'Nos vamos de vacaciones la próxima semana.', 5, 0),
  ('mes', 'month', 'noun', 'Enero es el primer mes del año.', 5, 0),
  ('año', 'year', 'noun', 'Feliz Año Nuevo.', 5, 0),
  ('siglo', 'century', 'noun', 'Vivimos en el siglo veintiuno.', 5, 0),
  ('estación', 'season/station', 'noun', 'El verano es mi estación favorita.', 5, 0),
  ('primavera', 'spring', 'noun', 'Las flores nacen en primavera.', 5, 0),
  ('verano', 'summer', 'noun', 'Hace calor en verano.', 5, 0),
  ('otoño', 'autumn/fall', 'noun', 'Las hojas caen en otoño.', 5, 0),
  ('invierno', 'winter', 'noun', 'En invierno hace mucho frío.', 5, 0),
  ('lunes', 'Monday', 'noun', 'Odio los lunes.', 5, 0),
  ('martes', 'Tuesday', 'noun', 'El martes tengo clase de tenis.', 5, 0),
  ('miércoles', 'Wednesday', 'noun', 'El miércoles es mitad de semana.', 5, 0),
  ('jueves', 'Thursday', 'noun', 'Este jueves voy al cine.', 5, 0),
  ('viernes', 'Friday', 'noun', 'Por fin es viernes.', 5, 0),
  ('sábado', 'Saturday', 'noun', 'El sábado hay una fiesta.', 5, 0),
  ('domingo', 'Sunday', 'noun', 'Los domingos descanso.', 5, 0),
  ('enero', 'January', 'noun', 'Nací en enero.', 5, 0),
  ('febrero', 'February', 'noun', 'Febrero es el mes más corto.', 5, 0),
  ('marzo', 'March', 'noun', 'En marzo empieza la primavera aquí.', 5, 0),
  ('abril', 'April', 'noun', 'Aguas mil en abril.', 5, 0),
  ('mayo', 'May', 'noun', 'Mi madre cumple años en mayo.', 5, 0),
  ('junio', 'June', 'noun', 'En junio terminan las clases.', 5, 0),
  ('julio', 'July', 'noun', 'Me voy de vacaciones en julio.', 5, 0),
  ('agosto', 'August', 'noun', 'Hace demasiado calor en agosto.', 5, 0),
  ('septiembre', 'September', 'noun', 'En septiembre vuelvo a estudiar.', 5, 0),
  ('octubre', 'October', 'noun', 'Halloween es en octubre.', 5, 0),
  ('noviembre', 'November', 'noun', 'Hace frío en noviembre.', 5, 0),
  ('diciembre', 'December', 'noun', 'Navidad es en diciembre.', 5, 0),
  ('uno', 'one', 'number', 'Quiero un café, por favor.', 5, 0),
  ('dos', 'two', 'number', 'Tengo dos perros.', 5, 0),
  ('tres', 'three', 'number', 'Somos tres hermanos.', 5, 0),
  ('cuatro', 'four', 'number', 'El coche tiene cuatro puertas.', 5, 0),
  ('cinco', 'five', 'number', 'Faltan cinco kilómetros.', 5, 0),
  ('seis', 'six', 'number', 'Me levanto a las seis de la mañana.', 5, 0),
  ('siete', 'seven', 'number', 'Trabajo los siete días de la semana.', 5, 0),
  ('ocho', 'eight', 'number', 'Duermo ocho horas diarias.', 5, 0),
  ('nueve', 'nine', 'number', 'Mi número de la suerte es el nueve.', 5, 0),
  ('diez', 'ten', 'number', 'Costó diez euros.', 5, 0),
  ('veinte', 'twenty', 'number', 'Cumplo veinte años.', 5, 0),
  ('treinta', 'thirty', 'number', 'El autobús llegó treinta minutos tarde.', 5, 0),
  ('cuarenta', 'forty', 'number', 'Mi padre tiene cuarenta años.', 5, 0),
  ('cincuenta', 'fifty', 'number', 'Cincuenta sombras de Grey.', 5, 0),
  ('cien', 'hundred/one hundred', 'number', 'Pagué cien dólares.', 5, 0),
  ('mil', 'thousand', 'number', 'Aquel vestido vale mil pesos.', 5, 0),
  ('millón', 'million', 'number', 'Un millón de gracias.', 5, 0),
  ('primero', 'first', 'adjective', 'Esta es mi primera vez aquí.', 5, 0),
  ('segundo', 'second', 'adjective', 'Piso segundo, puerta B.', 5, 0),
  ('tercero', 'third', 'adjective', 'Quedó el tercero de la carrera.', 5, 0),
  ('venir', 'to come (irregular e->ie)', 'verb', 'Vengo de muy lejos.', 3, 0),
  ('querer', 'to want/love (irregular e->ie)', 'verb', 'Te quiero con toda mi alma.', 3, 0),
  ('hacer', 'to do/make (irregular)', 'verb', '¿Qué vas a hacer hoy?', 3, 0),
  ('decir', 'to say/tell (irregular e->i)', 'verb', 'Siempre me dice la verdad.', 3, 0),
  ('poder', 'to be able to/can (irregular o->ue)', 'verb', '¿Puedo pasar?', 3, 0),
  ('poner', 'to put/place (irregular)', 'verb', 'Pon las llaves aquí.', 3, 0),
  ('salir', 'to leave/go out (irregular)', 'verb', 'Salgo del trabajo a las seis.', 3, 0),
  ('dar', 'to give (irregular)', 'verb', 'Dame tu mano.', 3, 0),
  ('saber', 'to know (irregular)', 'verb', 'Yo no sé nada.', 3, 0),
  ('conocer', 'to know a person/place (irregular)', 'verb', 'Conozco a tu hermana.', 3, 0),
  ('pensar', 'to think (irregular e->ie)', 'verb', 'Pienso que es mejor así.', 3, 0),
  ('empezar', 'to begin/start (irregular e->ie)', 'verb', 'La clase empieza ahora.', 3, 0),
  ('entender', 'to understand (irregular e->ie)', 'verb', 'Sigo sin entender.', 3, 0),
  ('sentir', 'to feel/regret (irregular e->ie)', 'verb', 'Lo siento muchísimo.', 3, 0),
  ('dormir', 'to sleep (irregular o->ue)', 'verb', 'Intento dormir ocho horas.', 3, 0),
  ('pedir', 'to ask for/request (irregular e->i)', 'verb', 'Voy a pedir dinero prestado.', 3, 0),
  ('seguir', 'to follow/continue (irregular e->i)', 'verb', 'Sigue todo recto.', 3, 0),
  ('volver', 'to return/go back (irregular o->ue)', 'verb', 'Vuelvo en un rato.', 3, 0),
  ('encontrar', 'to find (irregular o->ue)', 'verb', 'No encuentro mi cartera.', 3, 0),
  ('jugar', 'to play (irregular u->ue)', 'verb', 'Vamos a jugar un rato.', 3, 0),
  ('mostrar', 'to show (irregular o->ue)', 'verb', 'Muéstrame el camino.', 3, 0),
  ('viaje', 'trip/journey', 'noun', '¡Feliz viaje!', 10, 0),
  ('coche / carro/ auto', 'car', 'noun', 'Vamos en coche.', 10, 0),
  ('tren', 'train', 'noun', 'El tren de alta velocidad.', 10, 0),
  ('avión', 'airplane', 'noun', 'Nunca he viajado en avión.', 10, 0),
  ('aeropuerto', 'airport', 'noun', 'Llegamos al aeropuerto temprano.', 10, 0),
  ('boleto / billete', 'ticket', 'noun', 'Un billete de ida, por favor.', 10, 0),
  ('equipaje', 'luggage', 'noun', 'Hemos perdido mi equipaje.', 10, 0),
  ('hotel', 'hotel', 'noun', 'Un hotel de cinco estrellas.', 10, 0),
  ('habitación', 'room', 'noun', 'Una habitación doble.', 10, 0),
  ('reserva', 'reservation', 'noun', 'Tengo una reserva a mi nombre.', 10, 0),
  ('mapa', 'map', 'noun', 'Mira el mapa en tu celular.', 10, 0),
  ('calle', 'street', 'noun', 'Cruza la calle con cuidado.', 10, 0),
  ('ciudad', 'city', 'noun', 'Es una ciudad muy ruidosa.', 10, 0),
  ('pueblo', 'town/village', 'noun', 'Viven en un pueblo pequeño.', 10, 0),
  ('campo', 'country/field', 'noun', 'Fin de semana en el campo.', 10, 0),
  ('lugar', 'place', 'noun', 'Este es mi lugar favorito.', 10, 0),
  ('país', 'country', 'noun', 'Visité tres países en Europa.', 10, 0),
  ('mundo', 'world', 'noun', 'Quiero dar la vuelta al mundo.', 10, 0),
  ('sol', 'sun', 'noun', 'Hoy hace mucho sol.', 10, 0),
  ('luna', 'moon', 'noun', 'Hay luna llena esta noche.', 10, 0),
  ('estrella', 'star', 'noun', 'Cuenta las estrellas.', 10, 0),
  ('cielo', 'sky', 'noun', 'El cielo está muy azul.', 10, 0),
  ('lluvia', 'rain', 'noun', 'La lluvia cae suavemente.', 10, 0),
  ('nieve', 'snow', 'noun', 'Me encanta jugar en la nieve.', 10, 0),
  ('viento', 'wind', 'noun', 'Hace un viento helado.', 10, 0),
  ('árbol', 'tree', 'noun', 'El pájaro está en el árbol.', 10, 0),
  ('flor', 'flower', 'noun', 'Le compré unas flores hermosas.', 10, 0),
  ('río', 'river', 'noun', 'Nos bañamos en el río.', 10, 0),
  ('lago', 'lake', 'noun', 'Tienen una casa en el lago.', 10, 0),
  ('mar', 'sea', 'noun', 'Nadar en el mar.', 10, 0),
  ('playa', 'beach', 'noun', 'Día soleado en la playa.', 10, 0),
  ('montaña', 'mountain', 'noun', 'Subimos a la montaña.', 10, 0),
  ('fuego', 'fire', 'noun', '¡Cuidado con el fuego!', 10, 0),
  ('tierra', 'earth/land/dirt', 'noun', 'Tenemos los pies en la tierra.', 10, 0),
  ('animal', 'animal', 'noun', 'Me gustan mucho los animales.', 10, 0),
  ('perro', 'dog', 'noun', 'Saca a pasear al perro.', 10, 0),
  ('gato', 'cat', 'noun', 'El gato duerme en el sofá.', 10, 0),
  ('pájaro', 'bird', 'noun', 'El pájaro canta por la mañana.', 10, 0),
  ('pez', 'fish (alive)', 'noun', 'En el acuario hay muchos peces.', 10, 0),
  ('color', 'color', 'noun', '¿Cuál es tu color favorito?', 10, 0),
  ('rojo', 'red', 'adjective', 'Tiene un vestido rojo.', 10, 0),
  ('azul', 'blue', 'adjective', 'El cielo está más azul hoy.', 10, 0),
  ('verde', 'green', 'adjective', 'La hierba es verde.', 10, 0),
  ('amarillo', 'yellow', 'adjective', 'Un taxi amarillo brillante.', 10, 0),
  ('negro', 'black', 'adjective', 'Un gato negro cruzó la calle.', 10, 0),
  ('blanco', 'white', 'adjective', 'Nubes blancas en el cielo.', 10, 0),
  ('gris', 'gray', 'adjective', 'Hoy es un día gris y triste.', 10, 0),
  ('marrón', 'brown', 'adjective', 'Sus ojos son muy marrones.', 10, 0),
  ('naranja', 'orange', 'adjective', 'Una camisa naranja neón.', 10, 0),
  ('rosa', 'pink', 'adjective', 'Su cuarto está pintado de rosa.', 10, 0),
  ('blanco/claro', 'clear/light (color)', 'adjective', 'Un azul muy claro.', 10, 0),
  ('oscuro', 'dark (color)', 'adjective', 'Me gusta el azul oscuro.', 10, 0),
  ('brillante', 'shiny/bright', 'adjective', 'Una estrella muy brillante.', 10, 0),
  ('opaco', 'opaque/dull', 'adjective', 'Un cristal opaco.', 10, 0),
  ('ruidoso', 'noisy/loud', 'adjective', 'Es un bar demasiado ruidoso.', 10, 0),
  ('silencioso', 'quiet/silent', 'adjective', 'La biblioteca es muy silenciosa.', 10, 0),
  ('suave', 'soft', 'adjective', 'Una manta muy suave.', 10, 0),
  ('áspero', 'rough', 'adjective', 'Tiene las manos ásperas.', 10, 0),
  ('dulce', 'sweet', 'adjective', 'Este postre es muy dulce.', 10, 0),
  ('salado', 'salty', 'adjective', 'La sopa está muy salada.', 10, 0),
  ('amargo', 'bitter', 'adjective', 'El café negro es muy amargo.', 10, 0),
  ('picante', 'spicy', 'adjective', 'La salsa mexicana es picante.', 10, 0),
  ('ácido', 'sour', 'adjective', 'El limón es muy ácido.', 10, 0),
  ('sistema', 'system', 'noun', 'El sistema está roto.', 10, 0),
  ('problema', 'problem', 'noun', 'No hay ningún problema.', 10, 0),
  ('programa', 'program', 'noun', 'Cuál es tu programa favorito.', 10, 0),
  ('punto', 'point', 'noun', 'Llegaste al punto principal.', 10, 0),
  ('estado', 'state/condition', 'noun', 'El estado de la economía.', 10, 0),
  ('forma', 'shape/form/way', 'noun', 'Una forma diferente de ver las cosas.', 10, 0),
  ('parte', 'part/portion', 'noun', 'Te toca esta parte.', 10, 0),
  ('lugar', 'place', 'noun', 'Pon cada cosa en su lugar.', 10, 0),
  ('caso', 'case', 'noun', 'En cualquier caso, no importa.', 10, 0),
  ('vez', 'time/instance', 'noun', 'Había una vez...', 10, 0),
  ('idea', 'idea', 'noun', '¡Qué buena idea!', 10, 0),
  ('verdad', 'truth', 'noun', 'Dime la pura verdad.', 10, 0),
  ('realidad', 'reality', 'noun', 'En realidad no sé.', 10, 0),
  ('cambio', 'change', 'noun', 'El mundo necesita un cambio.', 10, 0),
  ('razón', 'reason/right', 'noun', 'Tienes toda la razón del mundo.', 10, 0),
  ('cuenta', 'account/bill', 'noun', 'La cuenta, por favor.', 10, 0),
  ('modo', 'way/manner', 'noun', 'De este modo es más fácil.', 10, 0),
  ('nivel', 'level', 'noun', 'Estás a un nivel avanzado.', 10, 0),
  ('Fín', 'end', 'phrase', 'El fín justifica los medios.', 10, 0),
  ('claro', 'clear', 'adjective', 'Está muy claro.', 10, 0),
  ('directo', 'direct', 'adjective', 'Un vuelo directo.', 10, 0),
  ('seguro', 'sure', 'adjective', 'Estoy muy seguro.', 10, 0),
  ('posible', 'possible', 'adjective', 'Sí, es posible.', 10, 0),
  ('diferente', 'different', 'adjective', 'Es algo diferente.', 10, 0),
  ('fuerte', 'strong', 'adjective', 'Un café fuerte.', 10, 0);
